export { FontPlugin } from "./fontPlugin";
export {
  CLEAR_FONT_STYLE_COMMAND,
  INCREASE_FONT_SIZE_COMMAND,
  DECREASE_FONT_SIZE_COMMAND,
  SET_FONT_SIZE_COMMAND,
  FONT_SIZE_CHANGED_COMMAND,
  SET_FONT_FAMILY_COMMAND,
  FONT_FAMILY_CHANGED_COMMAND,
} from "./fontCommands";
