export { FontPlugin } from "./fontPlugin";
export {
  CLEAR_FONT_STYLE_CMD,
  INCREASE_FONT_SIZE_CMD,
  DECREASE_FONT_SIZE_CMD,
  SET_FONT_SIZE_CMD,
  FONT_SIZE_CHANGED_CMD,
  SET_FONT_FAMILY_CMD,
  FONT_FAMILY_CHANGED_CMD,
} from "./fontCommands";
