/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

'use strict';let aa={},ca={},da={},ea={},fa={},ia={},ja={},na={},oa={},pa={},ra={},sa={},ta={},ua={},va={},wa={},xa={},za={},Aa={},Ba={},Ca={},Da={},Ea={},Ha={},Ia={},Ja={},Ka={},La={},Ma={},Na={},Oa={},Pa={},Qa={},Ra={},Sa={},Ta={},Ua="undefined"!==typeof window&&"undefined"!==typeof window.document&&"undefined"!==typeof window.document.createElement,Va=Ua&&"documentMode"in document?document.documentMode:null,n=Ua&&/Mac|iPod|iPhone|iPad/.test(navigator.platform),Wa=Ua&&/^(?!.*Seamonkey)(?=.*Firefox).*/i.test(navigator.userAgent),
Xa=Ua&&"InputEvent"in window&&!Va?"getTargetRanges"in new window.InputEvent("input"):!1,Za=Ua&&/Version\/[\d.]+.*Safari/.test(navigator.userAgent),$a=Ua&&/iPad|iPhone|iPod/.test(navigator.userAgent)&&!window.MSStream,ab=Ua&&/Android/.test(navigator.userAgent),bb=Ua&&/^(?=.*Chrome).*/i.test(navigator.userAgent),cb=Ua&&ab&&bb,db=Ua&&/AppleWebKit\/[\d.]+/.test(navigator.userAgent)&&!bb,eb=Za||$a||db?"\u00a0":"\u200b",fb=Wa?"\u00a0":eb,gb=/^[^A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]*[\u0591-\u07ff\ufb1d-\ufdfd\ufe70-\ufefc]/,
hb=/^[^\u0591-\u07ff\ufb1d-\ufdfd\ufe70-\ufefc]*[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]/,ib={bold:1,code:16,highlight:128,italic:2,strikethrough:4,subscript:32,superscript:64,underline:8},jb={directionless:1,unmergeable:2},kb={center:2,end:6,justify:4,left:1,right:3,start:5},lb={2:"center",6:"end",4:"justify",1:"left",3:"right",5:"start"},pb={normal:0,segmented:2,token:1},qb={0:"normal",2:"segmented",1:"token"};
var t;function rb(a){let b=new URLSearchParams;b.append("code",a);for(let c=1;c<arguments.length;c++)b.append("v",arguments[c]);throw Error(`Minified Lexical error #${a}; visit https://lexical.dev/docs/error?${b} for the full message or `+"use the non-minified dev environment for full errors and additional helpful warnings.");}t=rb&&rb.__esModule&&Object.prototype.hasOwnProperty.call(rb,"default")?rb["default"]:rb;
function sb(...a){let b=[];for(let c of a)if(c&&"string"===typeof c)for(let [d]of c.matchAll(/\S+/g))b.push(d);return b}let tb=!1,ub=0;function vb(a){ub=a.timeStamp}function wb(a,b,c){return b.__lexicalLineBreak===a||void 0!==a[`__lexicalKey_${c._key}`]}function xb(a){return a.getEditorState().read(()=>{let b=u();return null!==b?b.clone():null})}
function yb(a,b,c){tb=!0;let d=100<performance.now()-ub;try{v(a,()=>{let e=u()||xb(a);var f=new Map,g=a.getRootElement(),h=a._editorState,k=a._blockCursorElement;let l=!1,p="";for(var q=0;q<b.length;q++){var m=b[q],r=m.type,w=m.target,A=zb(w,h);if(!(null===A&&w!==g||y(A)))if("characterData"===r){if(m=d&&B(A))a:{m=e;r=w;var x=A;if(C(m)){var z=m.anchor.getNode();if(z.is(x)&&m.format!==z.getFormat()){m=!1;break a}}m=3===r.nodeType&&x.isAttached()}m&&(x=Ab(a._window),r=m=null,null!==x&&x.anchorNode===
w&&(m=x.anchorOffset,r=x.focusOffset),w=w.nodeValue,null!==w&&Bb(A,w,m,r,!1))}else if("childList"===r){l=!0;r=m.addedNodes;for(x=0;x<r.length;x++){z=r[x];var ba=Cb(z),ha=z.parentNode;null==ha||z===k||null!==ba||"BR"===z.nodeName&&wb(z,ha,a)||(Wa&&(ba=z.innerText||z.nodeValue)&&(p+=ba),ha.removeChild(z))}m=m.removedNodes;r=m.length;if(0<r){x=0;for(z=0;z<r;z++)if(ha=m[z],"BR"===ha.nodeName&&wb(ha,w,a)||k===ha)w.appendChild(ha),x++;r!==x&&(w===g&&(A=h._nodeMap.get("root")),f.set(w,A))}}}if(0<f.size)for(let [Ya,
ma]of f)if(E(ma))for(f=ma.getChildrenKeys(),g=Ya.firstChild,h=0;h<f.length;h++)k=a.getElementByKey(f[h]),null!==k&&(null==g?(Ya.appendChild(k),g=k):g!==k&&Ya.replaceChild(k,g),g=g.nextSibling);else B(ma)&&ma.markDirty();f=c.takeRecords();if(0<f.length){for(g=0;g<f.length;g++)for(k=f[g],h=k.addedNodes,k=k.target,q=0;q<h.length;q++)A=h[q],w=A.parentNode,null==w||"BR"!==A.nodeName||wb(A,k,a)||w.removeChild(A);c.takeRecords()}null!==e&&(l&&(e.dirty=!0,Db(e)),Wa&&Eb(a)&&e.insertRawText(p))})}finally{tb=
!1}}function Fb(a){let b=a._observer;if(null!==b){let c=b.takeRecords();yb(a,c,b)}}function Gb(a){0===ub&&Hb(a).addEventListener("textInput",vb,!0);a._observer=new MutationObserver((b,c)=>{yb(a,b,c)})}function Ib(a,b){let c=a.__mode,d=a.__format;a=a.__style;let e=b.__mode,f=b.__format;b=b.__style;return(null===c||c===e)&&(null===d||d===f)&&(null===a||a===b)}function Jb(a,b){let c=a.mergeWithSibling(b),d=F()._normalizedNodes;d.add(a.__key);d.add(b.__key);return c}
function Kb(a){if(""===a.__text&&a.isSimpleText()&&!a.isUnmergeable())a.remove();else{for(var b;null!==(b=a.getPreviousSibling())&&B(b)&&b.isSimpleText()&&!b.isUnmergeable();)if(""===b.__text)b.remove();else{Ib(b,a)&&(a=Jb(b,a));break}for(var c;null!==(c=a.getNextSibling())&&B(c)&&c.isSimpleText()&&!c.isUnmergeable();)if(""===c.__text)c.remove();else{Ib(a,c)&&Jb(a,c);break}}}function Lb(a){Mb(a.anchor);Mb(a.focus);return a}
function Mb(a){for(;"element"===a.type;){var b=a.getNode(),c=a.offset;c===b.getChildrenSize()?(b=b.getChildAtIndex(c-1),c=!0):(b=b.getChildAtIndex(c),c=!1);if(B(b)){a.set(b.__key,c?b.getTextContentSize():0,"text");break}else if(!E(b))break;a.set(b.__key,c?b.getChildrenSize():0,"element")}}let Nb=1,Ob="function"===typeof queueMicrotask?queueMicrotask:a=>{Promise.resolve().then(a)};
function Pb(a){let b=document.activeElement;if(null===b)return!1;let c=b.nodeName;return y(zb(a))&&("INPUT"===c||"TEXTAREA"===c||"true"===b.contentEditable&&null==b.__lexicalEditor)}function Qb(a,b,c){let d=a.getRootElement();try{return null!==d&&d.contains(b)&&d.contains(c)&&null!==b&&!Pb(b)&&Rb(b)===a}catch(e){return!1}}function Rb(a){for(;null!=a;){let b=a.__lexicalEditor;if(null!=b)return b;a=Sb(a)}return null}function Zb(a){return a.isToken()||a.isSegmented()}
function $b(a){for(;null!=a;){if(3===a.nodeType)return a;a=a.firstChild}return null}function ac(a,b,c){let d=ib[b];if(null!==c&&(a&d)===(c&d))return a;a^=d;"subscript"===b?a&=~ib.superscript:"superscript"===b&&(a&=~ib.subscript);return a}function bc(a,b){if(null!=b)a.__key=b;else{G();99<cc&&t(6);b=F();var c=dc(),d=""+Nb++;c._nodeMap.set(d,a);E(a)?b._dirtyElements.set(d,!0):b._dirtyLeaves.add(d);b._cloneNotNeeded.add(d);b._dirtyType=1;a.__key=d}}
function ec(a){var b=a.getParent();if(null!==b){let e=a.getWritable();b=b.getWritable();var c=a.getPreviousSibling();a=a.getNextSibling();if(null===c)if(null!==a){var d=a.getWritable();b.__first=a.__key;d.__prev=null}else b.__first=null;else{d=c.getWritable();if(null!==a){let f=a.getWritable();f.__prev=d.__key;d.__next=f.__key}else d.__next=null;e.__prev=null}null===a?null!==c?(a=c.getWritable(),b.__last=c.__key,a.__next=null):b.__last=null:(a=a.getWritable(),null!==c?(c=c.getWritable(),c.__next=
a.__key,a.__prev=c.__key):a.__prev=null,e.__next=null);b.__size--;e.__parent=null}}function fc(a){99<cc&&t(6);var b=a.getLatest(),c=b.__parent,d=dc();let e=F(),f=d._nodeMap;d=e._dirtyElements;if(null!==c)a:for(;null!==c;){if(d.has(c))break a;let g=f.get(c);if(void 0===g)break;d.set(c,!1);c=g.__parent}b=b.__key;e._dirtyType=1;E(a)?d.set(b,!0):e._dirtyLeaves.add(b)}
function H(a){G();var b=F();let c=b._compositionKey;a!==c&&(b._compositionKey=a,null!==c&&(b=I(c),null!==b&&b.getWritable()),null!==a&&(a=I(a),null!==a&&a.getWritable()))}function gc(){return hc()?null:F()._compositionKey}function I(a,b){a=(b||dc())._nodeMap.get(a);return void 0===a?null:a}function Cb(a,b){let c=F();a=a[`__lexicalKey_${c._key}`];return void 0!==a?I(a,b):null}function zb(a,b){for(;null!=a;){let c=Cb(a,b);if(null!==c)return c;a=Sb(a)}return null}
function ic(a){let b=Object.assign({},a._decorators);return a._pendingDecorators=b}function jc(a){return a.read(()=>J().getTextContent())}function kc(a,b){v(a,()=>{var c=dc();if(!c.isEmpty())if("root"===b)J().markDirty();else{c=c._nodeMap;for(let [,d]of c)d.markDirty()}},null===a._pendingEditorState?{tag:"history-merge"}:void 0)}function J(){return dc()._nodeMap.get("root")}function Db(a){G();let b=dc();null!==a&&(a.dirty=!0,a.setCachedNodes(null));b._selection=a}
function lc(a){var b=F(),c;a:{for(c=a;null!=c;){let d=c[`__lexicalKey_${b._key}`];if(void 0!==d){c=d;break a}c=Sb(c)}c=null}return null===c?(b=b.getRootElement(),a===b?I("root"):null):I(c)}function mc(a){return/[\uD800-\uDBFF][\uDC00-\uDFFF]/g.test(a)}function nc(a){let b=[];for(;null!==a;)b.push(a),a=a._parentEditor;return b}function oc(){return Math.random().toString(36).replace(/[^a-z]+/g,"").substr(0,5)}
function pc(a,b,c){b=Ab(b._window);if(null!==b){var d=b.anchorNode,{anchorOffset:e,focusOffset:f}=b;if(null!==d&&(b=3===d.nodeType?d.nodeValue:null,d=zb(d),null!==b&&B(d))){if(b===eb&&c){let g=c.length;b=c;f=e=g}null!==b&&Bb(d,b,e,f,a)}}}
function Bb(a,b,c,d,e){let f=a;if(f.isAttached()&&(e||!f.isDirty())){let l=f.isComposing(),p=b;(l||e)&&b[b.length-1]===eb&&(p=b.slice(0,-1));b=f.getTextContent();if(e||p!==b)if(""===p)if(H(null),Za||$a||db)f.remove();else{let q=F();setTimeout(()=>{q.update(()=>{f.isAttached()&&f.remove()})},20)}else{e=f.getParent();b=qc();var g=f.getTextContentSize(),h=gc(),k=f.getKey();f.isToken()||null!==h&&k===h&&!l||C(b)&&(null!==e&&!e.canInsertTextBefore()&&0===b.anchor.offset||b.anchor.key===a.__key&&0===b.anchor.offset&&
!f.canInsertTextBefore()&&!l||b.focus.key===a.__key&&b.focus.offset===g&&!f.canInsertTextAfter()&&!l)?f.markDirty():(a=u(),C(a)&&null!==c&&null!==d&&(a.setTextNodeRange(f,c,f,d),f.isSegmented()&&(c=f.getTextContent(),c=K(c),f.replace(c),f=c)),f.setTextContent(p))}}}
function rc(a,b){if(b.isSegmented())return!0;if(!a.isCollapsed())return!1;a=a.anchor.offset;let c=b.getParentOrThrow(),d=b.isToken();return 0===a?((a=!b.canInsertTextBefore()||!c.canInsertTextBefore()&&!b.isComposing()||d)||(b=b.getPreviousSibling(),a=(B(b)||E(b)&&b.isInline())&&!b.canInsertTextAfter()),a):a===b.getTextContentSize()?!b.canInsertTextAfter()||!c.canInsertTextAfter()&&!b.isComposing()||d:!1}function sc(a){return"Backspace"===a}
function tc(a,b){void 0===a.__lexicalClassNameCache&&(a.__lexicalClassNameCache={});let c=a.__lexicalClassNameCache,d=c[b];if(void 0!==d)return d;a=a[b];return"string"===typeof a?(a=sb(a),c[b]=a):a}function uc(a,b,c,d,e){0!==c.size&&(c=d.__type,d=d.__key,b=b.get(c),void 0===b&&t(22,c),c=b.klass,b=a.get(c),void 0===b&&(b=new Map,a.set(c,b)),a=b.get(d),c="destroyed"===a&&"created"===e,(void 0===a||c)&&b.set(d,c?"updated":e))}
function vc(a,b,c){let d=a.getParent(),e=c;null!==d&&(b&&0===c?(e=a.getIndexWithinParent(),a=d):b||c!==a.getChildrenSize()||(e=a.getIndexWithinParent()+1,a=d));return a.getChildAtIndex(b?e-1:e)}function wc(a,b){var c=a.offset;if("element"===a.type)return a=a.getNode(),vc(a,b,c);a=a.getNode();return b&&0===c||!b&&c===a.getTextContentSize()?(c=b?a.getPreviousSibling():a.getNextSibling(),null===c?vc(a.getParentOrThrow(),b,a.getIndexWithinParent()+(b?0:1)):c):null}
function Eb(a){a=(a=Hb(a).event)&&a.inputType;return"insertFromPaste"===a||"insertFromPasteAsQuotation"===a}function xc(a){return!L(a)&&!a.isLastChild()&&!a.isInline()}function yc(a,b){a=a._keyToDOMMap.get(b);void 0===a&&t(23,b);return a}function Sb(a){a=a.assignedSlot||a.parentElement;return null!==a&&11===a.nodeType?a.host:a}function zc(a,b){for(a=a.getParent();null!==a;){if(a.is(b))return!0;a=a.getParent()}return!1}function Hb(a){a=a._window;null===a&&t(24);return a}
function Ac(a){for(a=a.getParentOrThrow();null!==a&&!Bc(a);)a=a.getParentOrThrow();return a}function Bc(a){return L(a)||E(a)&&a.isShadowRoot()}function Cc(a){a=a.constructor.clone(a);bc(a,null);return a}function Dc(a){var b=F();let c=a.constructor.getType();b=b._nodes.get(c);void 0===b&&t(25);b=b.replace;return null!==b?(b=b(a),b instanceof a.constructor||t(26),b):a}function Ec(a,b){a=a.getParent();!L(a)||E(b)||y(b)||t(27)}function Fc(a){return(y(a)||E(a)&&!a.canBeEmpty())&&!a.isInline()}
function Gc(a,b,c){c.style.removeProperty("caret-color");b._blockCursorElement=null;b=a.parentElement;null!==b&&b.removeChild(a)}function Ab(a){return Ua?(a||window).getSelection():null}function Hc(a){return 1===a.nodeType}function Ic(a){return null!==a.nodeName.match(new RegExp(/^(a|abbr|acronym|b|cite|code|del|em|i|ins|kbd|label|output|q|ruby|s|samp|span|strong|sub|sup|time|u|tt|var|#text)$/,"i"))}
function Jc(a){if(L(a)||y(a)&&!a.isInline())return!0;if(!E(a)||Bc(a))return!1;var b=a.getFirstChild();b=null===b||Kc(b)||B(b)||b.isInline();return!a.isInline()&&!1!==a.canBeEmpty()&&b}function Lc(a,b){for(;null!==a&&null!==a.getParent()&&!b(a);)a=a.getParentOrThrow();return b(a)?a:null}function Mc(a,b,c,d,e,f){for(a=a.getFirstChild();null!==a;){let g=a.__key;a.__parent===b&&(E(a)&&Mc(a,g,c,d,e,f),c.has(g)||f.delete(g),e.push(g));a=a.getNextSibling()}}
function Nc(a,b,c,d){a=a._nodeMap;b=b._nodeMap;let e=[];for(let [f]of d){let g=b.get(f);void 0===g||g.isAttached()||(E(g)&&Mc(g,f,a,b,e,d),a.has(f)||d.delete(f),e.push(f))}for(let f of e)b.delete(f);for(let f of c)d=b.get(f),void 0===d||d.isAttached()||(a.has(f)||c.delete(f),b.delete(f))}let M="",N="",O=null,Oc="",Pc,R,Qc,Rc=!1,Sc=!1,Tc,Uc=null,Vc,ed,fd,gd,hd,id;
function jd(a,b){let c=fd.get(a);if(null!==b){let d=kd(a);d.parentNode===b&&b.removeChild(d)}gd.has(a)||R._keyToDOMMap.delete(a);E(c)&&(a=ld(c,fd),md(a,0,a.length-1,null));void 0!==c&&uc(id,Qc,Tc,c,"destroyed")}function md(a,b,c,d){for(;b<=c;++b){let e=a[b];void 0!==e&&jd(e,d)}}function nd(a,b){a.setProperty("text-align",b)}
function od(a,b){var c=Pc.theme.indent;if("string"===typeof c){let d=a.classList.contains(c);0<b&&!d?a.classList.add(c):1>b&&d&&a.classList.remove(c)}c=getComputedStyle(a).getPropertyValue("--lexical-indent-base-value")||"40px";a.style.setProperty("padding-inline-start",0===b?"":`calc(${b} * ${c})`)}function pd(a,b){a=a.style;0===b?nd(a,""):1===b?nd(a,"left"):2===b?nd(a,"center"):3===b?nd(a,"right"):4===b?nd(a,"justify"):5===b?nd(a,"start"):6===b&&nd(a,"end")}
function qd(a,b,c){let d=gd.get(a);void 0===d&&t(56);let e=d.createDOM(Pc,R);var f=R._keyToDOMMap;e["__lexicalKey_"+R._key]=a;f.set(a,e);B(d)?e.setAttribute("data-lexical-text","true"):y(d)&&e.setAttribute("data-lexical-decorator","true");if(E(d)){a=d.__indent;f=d.__size;0!==a&&od(e,a);if(0!==f){--f;a=ld(d,gd);var g=N;N="";rd(a,d,0,f,e,null);sd(d,e);N=g}a=d.__format;0!==a&&pd(e,a);d.isInline()||td(null,d,e);xc(d)&&(M+="\n\n",Oc+="\n\n")}else f=d.getTextContent(),y(d)?(g=d.decorate(R,Pc),null!==g&&
ud(a,g),e.contentEditable="false"):B(d)&&(d.isDirectionless()||(N+=f)),M+=f,Oc+=f;null!==b&&(null!=c?b.insertBefore(e,c):(c=b.__lexicalLineBreak,null!=c?b.insertBefore(e,c):b.appendChild(e)));uc(id,Qc,Tc,d,"created");return e}function rd(a,b,c,d,e,f){let g=M;for(M="";c<=d;++c){qd(a[c],e,f);let h=gd.get(a[c]);null!==h&&null===O&&B(h)&&(O=h.getFormat())}xc(b)&&(M+="\n\n");e.__lexicalTextContent=M;M=g+M}function vd(a,b){a=b.get(a);return Kc(a)||y(a)&&a.isInline()}
function td(a,b,c){a=null!==a&&(0===a.__size||vd(a.__last,fd));b=0===b.__size||vd(b.__last,gd);a?b||(b=c.__lexicalLineBreak,null!=b&&c.removeChild(b),c.__lexicalLineBreak=null):b&&(b=document.createElement("br"),c.__lexicalLineBreak=b,c.appendChild(b))}
function sd(a,b){var c=b.__lexicalDir;if(b.__lexicalDirTextContent!==N||c!==Uc){let f=""===N;if(f)var d=Uc;else d=N,d=gb.test(d)?"rtl":hb.test(d)?"ltr":null;if(d!==c){let g=b.classList,h=Pc.theme;var e=null!==c?h[c]:void 0;let k=null!==d?h[d]:void 0;void 0!==e&&("string"===typeof e&&(e=sb(e),e=h[c]=e),g.remove(...e));null===d||f&&"ltr"===d?b.removeAttribute("dir"):(void 0!==k&&("string"===typeof k&&(c=sb(k),k=h[d]=c),void 0!==k&&g.add(...k)),b.dir=d);Sc||(a.getWritable().__dir=d)}Uc=d;b.__lexicalDirTextContent=
N;b.__lexicalDir=d}}function ld(a,b){let c=[];for(a=a.__first;null!==a;){let d=b.get(a);void 0===d&&t(57);c.push(a);a=d.__next}return c}
function wd(a,b){var c=fd.get(a),d=gd.get(a);void 0!==c&&void 0!==d||t(58);var e=Rc||ed.has(a)||Vc.has(a);let f=yc(R,a);if(c===d&&!e)return E(c)?(d=f.__lexicalTextContent,void 0!==d&&(M+=d,Oc+=d),d=f.__lexicalDirTextContent,void 0!==d&&(N+=d)):(d=c.getTextContent(),B(c)&&!c.isDirectionless()&&(N+=d),Oc+=d,M+=d),f;c!==d&&e&&uc(id,Qc,Tc,d,"updated");if(d.updateDOM(c,f,Pc))return d=qd(a,null,null),null===b&&t(59),b.replaceChild(d,f),jd(a,null),d;if(E(c)&&E(d)){a=d.__indent;a!==c.__indent&&od(f,a);a=
d.__format;a!==c.__format&&pd(f,a);if(e){a=N;e=O;N="";O=null;b=M;var g=c.__size,h=d.__size;M="";if(1===g&&1===h){var k=c.__first,l=d.__first;if(k===l)wd(k,f);else{var p=kd(k),q=qd(l,null,null);f.replaceChild(q,p);jd(k,null)}k=gd.get(l);null===O&&B(k)&&(O=k.getFormat())}else{p=ld(c,fd);var m=ld(d,gd);if(0===g)0!==h&&rd(m,d,0,h-1,f,null);else if(0===h)0!==g&&(k=null==f.__lexicalLineBreak,md(p,0,g-1,k?null:f),k&&(f.textContent=""));else{q=p;p=m;m=g-1;g=h-1;let A=f.firstChild,x=0;for(h=0;x<=m&&h<=g;){var r=
q[x],w=p[h];if(r===w)A=xd(wd(w,f)),x++,h++;else{void 0===k&&(k=new Set(q));void 0===l&&(l=new Set(p));let z=l.has(r),ba=k.has(w);z?(ba?(r=yc(R,w),r===A?A=xd(wd(w,f)):(null!=A?f.insertBefore(r,A):f.appendChild(r),wd(w,f)),x++):qd(w,f,A),h++):(A=xd(kd(r)),jd(r,f),x++)}w=gd.get(w);null!==w&&null===O&&B(w)&&(O=w.getFormat())}k=x>m;l=h>g;k&&!l?(k=p[g+1],k=void 0===k?null:R.getElementByKey(k),rd(p,d,h,g,f,k)):l&&!k&&md(q,x,m,f)}}xc(d)&&(M+="\n\n");f.__lexicalTextContent=M;M=b+M;sd(d,f);yd(d)&&null!=O&&
O!==d.__textFormat&&!Sc&&(d.getWritable().__textFormat=O);N=a;O=e;L(d)||d.isInline()||td(c,d,f)}xc(d)&&(M+="\n\n",Oc+="\n\n")}else c=d.getTextContent(),y(d)?(e=d.decorate(R,Pc),null!==e&&ud(a,e)):B(d)&&!d.isDirectionless()&&(N+=c),M+=c,Oc+=c;!Sc&&L(d)&&d.__cachedText!==Oc&&(d.getWritable().__cachedText=Oc);return f}function ud(a,b){let c=R._pendingDecorators,d=R._decorators;if(null===c){if(d[a]===b)return;c=ic(R)}c[a]=b}
function xd(a){a=a.nextSibling;null!==a&&a===R._blockCursorElement&&(a=a.nextSibling);return a}function kd(a){let b=hd.get(a);void 0===b&&t(23,a);return b}let zd=Object.freeze({}),Gd=[["keydown",Ad],["pointerdown",Bd],["compositionstart",Cd],["compositionend",Dd],["input",Ed],["click",Fd],["cut",zd],["copy",zd],["dragstart",zd],["dragover",zd],["dragend",zd],["paste",zd],["focus",zd],["blur",zd],["drop",zd]];Xa&&Gd.push(["beforeinput",(a,b)=>Hd(a,b)]);
let Id=0,Jd=null,Kd=0,Ld=null,Md=new WeakMap,Nd=!1,Od=!1,Pd=!1,Qd=!1,Rd=[0,"",0,"root",0];
function Sd(a,b,c,d,e){let f=a.anchor,g=a.focus,h=f.getNode();var k=F();let l=Ab(k._window),p=null!==l?l.anchorNode:null,q=f.key;k=k.getElementByKey(q);let m=c.length;return q!==g.key||!B(h)||(!e&&(!Xa||Kd<d+50)||h.isDirty()&&2>m||mc(c))&&f.offset!==g.offset&&!h.isComposing()||Zb(h)||h.isDirty()&&1<m||(e||!Xa)&&null!==k&&!h.isComposing()&&p!==$b(k)||null!==l&&null!==b&&(!b.collapsed||b.startContainer!==l.anchorNode||b.startOffset!==l.anchorOffset)||h.getFormat()!==a.format||h.getStyle()!==a.style||
rc(a,h)}function Td(a,b){return null!==a&&null!==a.nodeValue&&3===a.nodeType&&0!==b&&b!==a.nodeValue.length}
function Ud(a,b,c){let {anchorNode:d,anchorOffset:e,focusNode:f,focusOffset:g}=a;if(Nd&&(Nd=!1,Td(d,e)&&Td(f,g)))return;v(b,()=>{if(!c)Db(null);else if(Qb(b,d,f)){var h=u();if(C(h)){var k=h.anchor,l=k.getNode();if(h.isCollapsed()){"Range"===a.type&&a.anchorNode===a.focusNode&&(h.dirty=!0);let [w,A,x,z]=Rd;var p=J();p=!1===b.isComposing()&&""===p.getTextContent();k.offset===x&&k.key===z?(h.format=w,h.style=A):"text"===k.type?(B(l)||t(52),h.format=l.getFormat(),h.style=l.getStyle()):"element"!==k.type||
p||(k=k.getNode(),k instanceof Vd&&0===k.getChildrenSize()?h.format=k.getTextFormat():(h.style="",h.format=0))}else{var q=k.key,m=h.focus.key;k=h.getNodes();l=k.length;var r=h.isBackward();p=r?g:e;let w=r?e:g,A=r?m:q;q=r?q:m;m=255;r=!1;for(let x=0;x<l;x++){let z=k[x],ba=z.getTextContentSize();if(B(z)&&0!==ba&&!(0===x&&z.__key===A&&p===ba||x===l-1&&z.__key===q&&0===w)&&(r=!0,m&=z.getFormat(),0===m))break}h.format=r?m:0}}S(b,aa,void 0)}})}
function Fd(a,b){v(b,()=>{let c=u();var d=Ab(b._window);let e=qc();if(d)if(C(c)){let g=c.anchor;var f=g.getNode();"element"===g.type&&0===g.offset&&c.isCollapsed()&&!L(f)&&1===J().getChildrenSize()&&f.getTopLevelElementOrThrow().isEmpty()&&null!==e&&c.is(e)?(d.removeAllRanges(),c.dirty=!0):3!==a.detail||c.isCollapsed()||(d=c.focus.getNode(),f!==d&&(E(f)?f.select(0):f.getParentOrThrow().select(0)))}else"touch"===a.pointerType&&(f=d.anchorNode,null!==f&&(f=f.nodeType,1===f||3===f))&&(d=Wd(e,d,b,a),
Db(d));S(b,ca,a)})}function Bd(a,b){let c=a.target;a=a.pointerType;c instanceof Node&&"touch"!==a&&v(b,()=>{y(zb(c))||(Od=!0)})}function Xd(a){if(!a.getTargetRanges)return null;a=a.getTargetRanges();return 0===a.length?null:a[0]}function Yd(a,b){return a!==b||E(a)||E(b)||!a.isToken()||!b.isToken()}
function Hd(a,b){let c=a.inputType,d=Xd(a);"deleteCompositionText"===c||Wa&&Eb(b)||"insertCompositionText"!==c&&v(b,()=>{var e=u();if("deleteContentBackward"===c){if(null===e){var f=qc();if(!C(f))return;Db(f.clone())}if(C(e)){f=e.anchor.key===e.focus.key;if("MediaLast"===Jd&&a.timeStamp<Id+30&&b.isComposing()&&f)H(null),Id=0,setTimeout(()=>{v(b,()=>{H(null)})},30),C(e)&&(f=e.anchor.getNode(),f.markDirty(),e.format=f.getFormat(),B(f)||t(53),e.style=f.getStyle());else{H(null);a.preventDefault();var g=
e.anchor.getNode().getTextContent();e=0===e.anchor.offset&&e.focus.offset===g.length;cb&&f&&!e||S(b,da,!0)}return}}if(C(e)){f=a.data;null!==Ld&&pc(!1,b,Ld);e.dirty&&null===Ld||!e.isCollapsed()||L(e.anchor.getNode())||null===d||e.applyDOMRange(d);Ld=null;var h=e.focus;g=e.anchor.getNode();h=h.getNode();if("insertText"===c||"insertTranspose"===c)"\n"===f?(a.preventDefault(),S(b,ea,!1)):"\n\n"===f?(a.preventDefault(),S(b,fa,void 0)):null==f&&a.dataTransfer?(f=a.dataTransfer.getData("text/plain"),a.preventDefault(),
e.insertRawText(f)):null!=f&&Sd(e,d,f,a.timeStamp,!0)?(a.preventDefault(),S(b,ia,f)):Ld=f,Kd=a.timeStamp;else switch(a.preventDefault(),c){case "insertFromYank":case "insertFromDrop":case "insertReplacementText":S(b,ia,a);break;case "insertFromComposition":H(null);S(b,ia,a);break;case "insertLineBreak":H(null);S(b,ea,!1);break;case "insertParagraph":H(null);Pd&&!$a?(Pd=!1,S(b,ea,!1)):S(b,fa,void 0);break;case "insertFromPaste":case "insertFromPasteAsQuotation":S(b,ja,a);break;case "deleteByComposition":Yd(g,
h)&&S(b,na,a);break;case "deleteByDrag":case "deleteByCut":S(b,na,a);break;case "deleteContent":S(b,da,!1);break;case "deleteWordBackward":S(b,oa,!0);break;case "deleteWordForward":S(b,oa,!1);break;case "deleteHardLineBackward":case "deleteSoftLineBackward":S(b,pa,!0);break;case "deleteContentForward":case "deleteHardLineForward":case "deleteSoftLineForward":S(b,pa,!1);break;case "formatStrikeThrough":S(b,ra,"strikethrough");break;case "formatBold":S(b,ra,"bold");break;case "formatItalic":S(b,ra,
"italic");break;case "formatUnderline":S(b,ra,"underline");break;case "historyUndo":S(b,sa,void 0);break;case "historyRedo":S(b,ta,void 0)}}})}
function Ed(a,b){a.stopPropagation();v(b,()=>{var c=u(),d=a.data,e=Xd(a);if(null!=d&&C(c)&&Sd(c,e,d,a.timeStamp,!1)){Qd&&(Zd(b,d),Qd=!1);var f=c.anchor.getNode();e=Ab(b._window);if(null===e)return;var g=c.isBackward();let h=g?c.anchor.offset:c.focus.offset,k=g?c.focus.offset:c.anchor.offset;if(g=Xa&&!c.isCollapsed()&&B(f)&&null!==e.anchorNode)f=f.getTextContent().slice(0,h)+d+f.getTextContent().slice(h+k),e=e.anchorNode,g=f===(3===e.nodeType?e.nodeValue:null);g||S(b,ia,d);d=d.length;Wa&&1<d&&"insertCompositionText"===
a.inputType&&!b.isComposing()&&(c.anchor.offset-=d);Za||$a||db||!b.isComposing()||(Id=0,H(null))}else pc(!1,b,null!==d?d:void 0),Qd&&(Zd(b,d||void 0),Qd=!1);G();c=F();Fb(c)});Ld=null}function Cd(a,b){v(b,()=>{let c=u();if(C(c)&&!b.isComposing()){let d=c.anchor,e=c.anchor.getNode();H(d.key);(a.timeStamp<Id+30||"element"===d.type||!c.isCollapsed()||e.getFormat()!==c.format||B(e)&&e.getStyle()!==c.style)&&S(b,ia,fb)}})}
function Zd(a,b){var c=a._compositionKey;H(null);if(null!==c&&null!=b){if(""===b){b=I(c);a=$b(a.getElementByKey(c));null!==a&&null!==a.nodeValue&&B(b)&&Bb(b,a.nodeValue,null,null,!0);return}if("\n"===b[b.length-1]&&(c=u(),C(c))){b=c.focus;c.anchor.set(b.key,b.offset,b.type);S(a,Ca,null);return}}pc(!0,a,b)}function Dd(a,b){Wa?Qd=!0:v(b,()=>{Zd(b,a.data)})}
function Ad(a,b){Id=a.timeStamp;Jd=a.key;if(!b.isComposing()){var {key:c,shiftKey:d,ctrlKey:e,metaKey:f,altKey:g}=a;if(!S(b,ua,a)&&null!=c){if("ArrowRight"!==c||e||f||g)if("ArrowRight"!==c||g||d||!e&&!f)if("ArrowLeft"!==c||e||f||g)if("ArrowLeft"!==c||g||d||!e&&!f)if("ArrowUp"!==c||e||f)if("ArrowDown"!==c||e||f)if("Enter"===c&&d)Pd=!0,S(b,Ca,a);else if(" "===c)S(b,Da,a);else if(n&&e&&"o"===c.toLowerCase())a.preventDefault(),Pd=!0,S(b,ea,!0);else if("Enter"!==c||d){var h=n?g||f?!1:sc(c)||"h"===c.toLowerCase()&&
e:e||g||f?!1:sc(c);if(h)sc(c)?S(b,Ea,a):(a.preventDefault(),S(b,da,!0));else if("Escape"===c)S(b,Ha,a);else if(h=n?d||g||f?!1:"Delete"===c||"d"===c.toLowerCase()&&e:e||g||f?!1:"Delete"===c,h)"Delete"===c?S(b,Ia,a):(a.preventDefault(),S(b,da,!1));else if(sc(c)&&(n?g:e))a.preventDefault(),S(b,oa,!0);else if("Delete"===c&&(n?g:e))a.preventDefault(),S(b,oa,!1);else if(n&&f&&sc(c))a.preventDefault(),S(b,pa,!0);else if(n&&f&&"Delete"===c)a.preventDefault(),S(b,pa,!1);else if("b"===c.toLowerCase()&&!g&&
(n?f:e))a.preventDefault(),S(b,ra,"bold");else if("u"===c.toLowerCase()&&!g&&(n?f:e))a.preventDefault(),S(b,ra,"underline");else if("i"===c.toLowerCase()&&!g&&(n?f:e))a.preventDefault(),S(b,ra,"italic");else if("Tab"!==c||g||e||f)if("z"===c.toLowerCase()&&!d&&(n?f:e))a.preventDefault(),S(b,sa,void 0);else if(h=n?"z"===c.toLowerCase()&&f&&d:"y"===c.toLowerCase()&&e||"z"===c.toLowerCase()&&e&&d,h)a.preventDefault(),S(b,ta,void 0);else if($d(b._editorState._selection))h=d?!1:"c"===c.toLowerCase()?n?
f:e:!1,h?(a.preventDefault(),S(b,Oa,a)):(h=d?!1:"x"===c.toLowerCase()?n?f:e:!1,h?(a.preventDefault(),S(b,Pa,a)):"a"===c.toLowerCase()&&(n?f:e)&&(a.preventDefault(),S(b,Qa,a)));else{if(h=!Wa)h="a"===c.toLowerCase()&&(n?f:e);h&&(a.preventDefault(),S(b,Qa,a))}else S(b,Ja,a)}else Pd=!1,S(b,Ca,a);else S(b,Ba,a);else S(b,Aa,a);else S(b,za,a);else S(b,xa,a);else S(b,wa,a);else S(b,va,a);(e||d||g||f)&&S(b,Ta,a)}}}
function ae(a){let b=a.__lexicalEventHandles;void 0===b&&(b=[],a.__lexicalEventHandles=b);return b}let be=new Map;
function ce(a){var b=a.target;let c=Ab(null==b?null:9===b.nodeType?b.defaultView:b.ownerDocument.defaultView);if(null!==c){var d=Rb(c.anchorNode);if(null!==d){Od&&(Od=!1,v(d,()=>{var h=qc(),k=c.anchorNode;null!==k&&(k=k.nodeType,1===k||3===k)&&(h=Wd(h,c,d,a),Db(h))}));b=nc(d);b=b[b.length-1];var e=b._key,f=be.get(e),g=f||b;g!==d&&Ud(c,g,!1);Ud(c,d,!0);d!==b?be.set(e,d):f&&be.delete(e)}}}
function de(a,b){var c=a.ownerDocument,d=Md.get(c);(void 0===d||1>d)&&c.addEventListener("selectionchange",ce);Md.set(c,(d||0)+1);a.__lexicalEditor=b;c=ae(a);for(d=0;d<Gd.length;d++){let [e,f]=Gd[d],g="function"===typeof f?h=>{!0!==h._lexicalHandled&&(h._lexicalHandled=!0,(b.isEditable()||"click"===e)&&f(h,b))}:h=>{if(!0!==h._lexicalHandled){h._lexicalHandled=!0;var k=b.isEditable();switch(e){case "cut":return k&&S(b,Pa,h);case "copy":return S(b,Oa,h);case "paste":return k&&S(b,ja,h);case "dragstart":return k&&
S(b,La,h);case "dragover":return k&&S(b,Ma,h);case "dragend":return k&&S(b,Na,h);case "focus":return k&&S(b,Ra,h);case "blur":return k&&S(b,Sa,h);case "drop":return k&&S(b,Ka,h)}}};a.addEventListener(e,g);c.push(()=>{a.removeEventListener(e,g)})}}
function ee(a,b,c){G();var d=a.__key;let e=a.getParent();if(null!==e){var f=u();if(C(f)&&E(a)){var {anchor:g,focus:h}=f;var k=g.getNode();var l=h.getNode();zc(k,a)&&g.set(a.__key,0,"element");zc(l,a)&&h.set(a.__key,0,"element")}k=f;l=!1;if(C(k)&&b){f=k.anchor;let p=k.focus;f.key===d&&(fe(f,a,e,a.getPreviousSibling(),a.getNextSibling()),l=!0);p.key===d&&(fe(p,a,e,a.getPreviousSibling(),a.getNextSibling()),l=!0)}else $d(k)&&b&&a.isSelected()&&a.selectPrevious();C(k)&&b&&!l?(d=a.getIndexWithinParent(),
ec(a),ge(k,e,d,-1)):ec(a);c||Bc(e)||e.canBeEmpty()||!e.isEmpty()||ee(e,b);b&&L(e)&&e.isEmpty()&&e.selectEnd()}}
class he{static getType(){t(60,this.name)}static clone(){t(61,this.name)}constructor(a){this.__type=this.constructor.getType();this.__next=this.__prev=this.__parent=null;bc(this,a)}getType(){return this.__type}isInline(){t(62,this.constructor.name)}isAttached(){for(var a=this.__key;null!==a;){if("root"===a)return!0;a=I(a);if(null===a)break;a=a.__parent}return!1}isSelected(a){a=a||u();if(null==a)return!1;let b=a.getNodes().some(c=>c.__key===this.__key);return B(this)?b:C(a)&&"element"===a.anchor.type&&
"element"===a.focus.type&&a.anchor.key===a.focus.key&&a.anchor.offset===a.focus.offset?!1:b}getKey(){return this.__key}getIndexWithinParent(){var a=this.getParent();if(null===a)return-1;a=a.getFirstChild();let b=0;for(;null!==a;){if(this.is(a))return b;b++;a=a.getNextSibling()}return-1}getParent(){let a=this.getLatest().__parent;return null===a?null:I(a)}getParentOrThrow(){let a=this.getParent();null===a&&t(63,this.__key);return a}getTopLevelElement(){let a=this;for(;null!==a;){let b=a.getParent();
if(Bc(b))return E(a)||t(64),a;a=b}return null}getTopLevelElementOrThrow(){let a=this.getTopLevelElement();null===a&&t(65,this.__key);return a}getParents(){let a=[],b=this.getParent();for(;null!==b;)a.push(b),b=b.getParent();return a}getParentKeys(){let a=[],b=this.getParent();for(;null!==b;)a.push(b.__key),b=b.getParent();return a}getPreviousSibling(){let a=this.getLatest().__prev;return null===a?null:I(a)}getPreviousSiblings(){let a=[];var b=this.getParent();if(null===b)return a;for(b=b.getFirstChild();null!==
b&&!b.is(this);)a.push(b),b=b.getNextSibling();return a}getNextSibling(){let a=this.getLatest().__next;return null===a?null:I(a)}getNextSiblings(){let a=[],b=this.getNextSibling();for(;null!==b;)a.push(b),b=b.getNextSibling();return a}getCommonAncestor(a){let b=this.getParents(),c=a.getParents();E(this)&&b.unshift(this);E(a)&&c.unshift(a);a=null;let d=Math.min(b.length,c.length);for(let e=1;e<=d&&b[b.length-e]===c[c.length-e];++e)a=b[b.length-e];return a}is(a){return null==a?!1:this.__key===a.__key}isBefore(a){if(this===
a||a.isParentOf(this))return!1;if(this.isParentOf(a))return!0;var b=this.getParents(),c=a.getParents();b.unshift(this);c.unshift(a);let d=null,e=Math.min(b.length,c.length);for(var f=1;f<=e&&b[b.length-f]===c[c.length-f];++f)d=b[b.length-f];if(a.is(d))return!1;if(this.is(d))return!0;a=b[b.length-f];c=c[c.length-f];f=a.getPreviousSibling();for(b=c.getPreviousSibling();;){if(null===f)return!0;if(null===b)return!1;if(a.is(b))return!0;if(c.is(f))return!1;f=f.getPreviousSibling();b=b.getPreviousSibling()}}isParentOf(a){let b=
this.__key;if(b===a.__key)return!1;for(;null!==a;){if(a.__key===b)return!0;a=a.getParent()}return!1}getNodesBetween(a){if(this===a)return[this];var b=this.isBefore(a),c=b?this:a;a=b?a:this;b=new Set;let d=[];for(var e=c;!e.is(a);){b.has(e)||(b.add(e),d.push(e));c=e;if(E(c)){let f=c.getFirstChild();c=null===f?c.getNextSibling():f}else c=c.getNextSibling();if(null===c){c=e.getParentOrThrow();b.has(c)||(b.add(c),d.push(c));for(e=c.getNextSibling();null===e;)c=c.getParentOrThrow(),b.has(c)||(b.add(c),
d.push(c)),e=c.getNextSibling();c=e}e=c}d.push(a);return d}isDirty(){let a=F()._dirtyLeaves;return null!==a&&a.has(this.__key)}getLatest(){let a=I(this.__key);null===a&&t(66);return a}getWritable(){G();var a=dc(),b=F();a=a._nodeMap;let c=this.__key,d=this.getLatest(),e=d.__parent;b=b._cloneNotNeeded;var f=u();null!==f&&f.setCachedNodes(null);if(b.has(c))return fc(d),d;f=d.constructor.clone(d);f.__parent=e;f.__next=d.__next;f.__prev=d.__prev;E(d)&&E(f)?(yd(d)&&yd(f)&&(f.__textFormat=d.__textFormat),
f.__first=d.__first,f.__last=d.__last,f.__size=d.__size,f.__indent=d.__indent,f.__format=d.__format,f.__dir=d.__dir):B(d)&&B(f)&&(f.__format=d.__format,f.__style=d.__style,f.__mode=d.__mode,f.__detail=d.__detail);b.add(c);f.__key=c;fc(f);a.set(c,f);return f}getTextContent(){return""}getTextContentSize(){return this.getTextContent().length}createDOM(){t(67)}updateDOM(){t(68)}exportDOM(a){return{element:this.createDOM(a._config,a)}}exportJSON(){t(69)}static importJSON(){t(10,this.name)}static transform(){return null}remove(a){ee(this,
!0,a)}replace(a,b){G();var c=u();null!==c&&(c=c.clone());Ec(this,a);let d=this.getLatest(),e=this.__key,f=a.__key,g=a.getWritable();a=this.getParentOrThrow().getWritable();let h=a.__size;ec(g);let k=d.getPreviousSibling(),l=d.getNextSibling(),p=d.__prev,q=d.__next,m=d.__parent;ee(d,!1,!0);null===k?a.__first=f:k.getWritable().__next=f;g.__prev=p;null===l?a.__last=f:l.getWritable().__prev=f;g.__next=q;g.__parent=m;a.__size=h;b&&(E(this)&&E(g)||t(70),this.getChildren().forEach(r=>{g.append(r)}));C(c)&&
(Db(c),b=c.anchor,c=c.focus,b.key===e&&ie(b,g),c.key===e&&ie(c,g));gc()===e&&H(f);return g}insertAfter(a,b=!0){G();Ec(this,a);var c=this.getWritable();let d=a.getWritable();var e=d.getParent();let f=u();var g=!1,h=!1;if(null!==e){var k=a.getIndexWithinParent();ec(d);C(f)&&(h=e.__key,g=f.anchor,e=f.focus,g="element"===g.type&&g.key===h&&g.offset===k+1,h="element"===e.type&&e.key===h&&e.offset===k+1)}e=this.getNextSibling();k=this.getParentOrThrow().getWritable();let l=d.__key,p=c.__next;null===e?k.__last=
l:e.getWritable().__prev=l;k.__size++;c.__next=l;d.__next=p;d.__prev=c.__key;d.__parent=c.__parent;b&&C(f)&&(b=this.getIndexWithinParent(),ge(f,k,b+1),c=k.__key,g&&f.anchor.set(c,b+2,"element"),h&&f.focus.set(c,b+2,"element"));return a}insertBefore(a,b=!0){G();Ec(this,a);var c=this.getWritable();let d=a.getWritable(),e=d.__key;ec(d);let f=this.getPreviousSibling(),g=this.getParentOrThrow().getWritable(),h=c.__prev,k=this.getIndexWithinParent();null===f?g.__first=e:f.getWritable().__next=e;g.__size++;
c.__prev=e;d.__prev=h;d.__next=c.__key;d.__parent=c.__parent;c=u();b&&C(c)&&(b=this.getParentOrThrow(),ge(c,b,k));return a}isParentRequired(){return!1}createParentElementNode(){return je()}selectStart(){return this.selectPrevious()}selectEnd(){return this.selectNext(0,0)}selectPrevious(a,b){G();let c=this.getPreviousSibling(),d=this.getParentOrThrow();return null===c?d.select(0,0):E(c)?c.select():B(c)?c.select(a,b):(a=c.getIndexWithinParent()+1,d.select(a,a))}selectNext(a,b){G();let c=this.getNextSibling(),
d=this.getParentOrThrow();return null===c?d.select():E(c)?c.select(0,0):B(c)?c.select(a,b):(a=c.getIndexWithinParent(),d.select(a,a))}markDirty(){this.getWritable()}}function ke(a,b){let c=b.getParentOrThrow().getLastChild(),d=b;for(b=[b];d!==c;)d.getNextSibling()||t(73),d=d.getNextSibling(),b.push(d);for(let e of b)a=a.insertAfter(e)}
class le extends he{static getType(){return"linebreak"}static clone(a){return new le(a.__key)}constructor(a){super(a)}getTextContent(){return"\n"}createDOM(){return document.createElement("br")}updateDOM(){return!1}static importDOM(){return{br:a=>{a:{var b=a.parentElement;if(null!==b){let c=b.firstChild;if(c===a||c.nextSibling===a&&me(c))if(b=b.lastChild,b===a||b.previousSibling===a&&me(b)){a=!0;break a}}a=!1}return a?null:{conversion:ne,priority:0}}}}static importJSON(){return oe()}exportJSON(){return{type:"linebreak",
version:1}}}function ne(){return{node:oe()}}function oe(){return Dc(new le)}function Kc(a){return a instanceof le}function me(a){return 3===a.nodeType&&/^( |\t|\r?\n)+$/.test(a.textContent||"")}function pe(a,b){return b&16?"code":b&128?"mark":b&32?"sub":b&64?"sup":null}function qe(a,b){return b&1?"strong":b&2?"em":"span"}
function re(a,b,c,d,e){a=d.classList;d=tc(e,"base");void 0!==d&&a.add(...d);d=tc(e,"underlineStrikethrough");let f=!1,g=b&8&&b&4;var h=c&8&&c&4;void 0!==d&&(h?(f=!0,g||a.add(...d)):g&&a.remove(...d));for(let k in ib)h=ib[k],d=tc(e,k),void 0!==d&&(c&h?!f||"underline"!==k&&"strikethrough"!==k?(0===(b&h)||g&&"underline"===k||"strikethrough"===k)&&a.add(...d):b&h&&a.remove(...d):b&h&&a.remove(...d))}
function se(a,b,c){let d=b.firstChild;c=c.isComposing();a+=c?eb:"";if(null==d)b.textContent=a;else if(b=d.nodeValue,b!==a)if(c||Wa){c=b.length;let e=a.length,f=0,g=0;for(;f<c&&f<e&&b[f]===a[f];)f++;for(;g+f<c&&g+f<e&&b[c-g-1]===a[e-g-1];)g++;a=[f,c-f-g,a.slice(f,e-g)];let [h,k,l]=a;0!==k&&d.deleteData(h,k);d.insertData(h,l)}else d.nodeValue=a}function te(a,b){b=document.createElement(b);b.appendChild(a);return b}
class ue extends he{static getType(){return"text"}static clone(a){return new ue(a.__text,a.__key)}constructor(a,b){super(b);this.__text=a;this.__format=0;this.__style="";this.__detail=this.__mode=0}getFormat(){return this.getLatest().__format}getDetail(){return this.getLatest().__detail}getMode(){let a=this.getLatest();return qb[a.__mode]}getStyle(){return this.getLatest().__style}isToken(){return 1===this.getLatest().__mode}isComposing(){return this.__key===gc()}isSegmented(){return 2===this.getLatest().__mode}isDirectionless(){return 0!==
(this.getLatest().__detail&1)}isUnmergeable(){return 0!==(this.getLatest().__detail&2)}hasFormat(a){a=ib[a];return 0!==(this.getFormat()&a)}isSimpleText(){return"text"===this.__type&&0===this.__mode}getTextContent(){return this.getLatest().__text}getFormatFlags(a,b){let c=this.getLatest().__format;return ac(c,a,b)}canHaveFormat(){return!0}createDOM(a){var b=this.__format,c=pe(this,b);let d=qe(this,b),e=document.createElement(null===c?d:c),f=e;this.hasFormat("code")&&e.setAttribute("spellcheck","false");
null!==c&&(f=document.createElement(d),e.appendChild(f));c=f;se(this.__text,c,this);a=a.theme.text;void 0!==a&&re(d,0,b,c,a);b=this.__style;""!==b&&(e.style.cssText=b);return e}updateDOM(a,b,c){let d=this.__text;var e=a.__format,f=this.__format,g=pe(this,e);let h=pe(this,f);var k=qe(this,e);let l=qe(this,f);if((null===g?k:g)!==(null===h?l:h))return!0;if(g===h&&k!==l)return e=b.firstChild,null==e&&t(39),a=g=document.createElement(l),se(d,a,this),c=c.theme.text,void 0!==c&&re(l,0,f,a,c),b.replaceChild(g,
e),!1;k=b;null!==h&&null!==g&&(k=b.firstChild,null==k&&t(40));se(d,k,this);c=c.theme.text;void 0!==c&&e!==f&&re(l,e,f,k,c);f=this.__style;a.__style!==f&&(b.style.cssText=f);return!1}static importDOM(){return{"#text":()=>({conversion:ve,priority:0}),b:()=>({conversion:we,priority:0}),code:()=>({conversion:xe,priority:0}),em:()=>({conversion:xe,priority:0}),i:()=>({conversion:xe,priority:0}),s:()=>({conversion:xe,priority:0}),span:()=>({conversion:ye,priority:0}),strong:()=>({conversion:xe,priority:0}),
sub:()=>({conversion:xe,priority:0}),sup:()=>({conversion:xe,priority:0}),u:()=>({conversion:xe,priority:0})}}static importJSON(a){let b=K(a.text);b.setFormat(a.format);b.setDetail(a.detail);b.setMode(a.mode);b.setStyle(a.style);return b}exportDOM(a){({element:a}=super.exportDOM(a));null!==a&&Hc(a)||t(41);a.style.whiteSpace="pre-wrap";this.hasFormat("bold")&&(a=te(a,"b"));this.hasFormat("italic")&&(a=te(a,"i"));this.hasFormat("strikethrough")&&(a=te(a,"s"));this.hasFormat("underline")&&(a=te(a,"u"));
return{element:a}}exportJSON(){return{detail:this.getDetail(),format:this.getFormat(),mode:this.getMode(),style:this.getStyle(),text:this.getTextContent(),type:"text",version:1}}selectionTransform(){}setFormat(a){let b=this.getWritable();b.__format="string"===typeof a?ib[a]:a;return b}setDetail(a){let b=this.getWritable();b.__detail="string"===typeof a?jb[a]:a;return b}setStyle(a){let b=this.getWritable();b.__style=a;return b}toggleFormat(a){let b=this.getFormat();a=ac(b,a,null);return this.setFormat(a)}toggleDirectionless(){let a=
this.getWritable();a.__detail^=1;return a}toggleUnmergeable(){let a=this.getWritable();a.__detail^=2;return a}setMode(a){a=pb[a];if(this.__mode===a)return this;let b=this.getWritable();b.__mode=a;return b}setTextContent(a){if(this.__text===a)return this;let b=this.getWritable();b.__text=a;return b}select(a,b){G();let c=u();var d=this.getTextContent();let e=this.__key;"string"===typeof d?(d=d.length,void 0===a&&(a=d),void 0===b&&(b=d)):b=a=0;if(C(c))d=gc(),d!==c.anchor.key&&d!==c.focus.key||H(e),c.setTextNodeRange(this,
a,this,b);else return ze(e,a,e,b,"text","text");return c}selectStart(){return this.select(0,0)}selectEnd(){let a=this.getTextContentSize();return this.select(a,a)}spliceText(a,b,c,d){let e=this.getWritable(),f=e.__text,g=c.length,h=a;0>h&&(h=g+h,0>h&&(h=0));let k=u();d&&C(k)&&(a+=g,k.setTextNodeRange(e,a,e,a));b=f.slice(0,h)+c+f.slice(h+b);e.__text=b;return e}canInsertTextBefore(){return!0}canInsertTextAfter(){return!0}splitText(...a){G();var b=this.getLatest(),c=b.getTextContent(),d=b.__key,e=gc(),
f=new Set(a);a=[];var g=c.length,h="";for(var k=0;k<g;k++)""!==h&&f.has(k)&&(a.push(h),h=""),h+=c[k];""!==h&&a.push(h);f=a.length;if(0===f)return[];if(a[0]===c)return[b];var l=a[0];c=b.getParentOrThrow();k=b.getFormat();let p=b.getStyle(),q=b.__detail;g=!1;b.isSegmented()?(h=K(l),h.__format=k,h.__style=p,h.__detail=q,g=!0):(h=b.getWritable(),h.__text=l);b=u();h=[h];l=l.length;for(let w=1;w<f;w++){var m=a[w],r=m.length;m=K(m).getWritable();m.__format=k;m.__style=p;m.__detail=q;let A=m.__key;r=l+r;
if(C(b)){let x=b.anchor,z=b.focus;x.key===d&&"text"===x.type&&x.offset>l&&x.offset<=r&&(x.key=A,x.offset-=l,b.dirty=!0);z.key===d&&"text"===z.type&&z.offset>l&&z.offset<=r&&(z.key=A,z.offset-=l,b.dirty=!0)}e===d&&H(A);l=r;h.push(m)}d=this.getPreviousSibling();e=this.getNextSibling();null!==d&&fc(d);null!==e&&fc(e);d=c.getWritable();e=this.getIndexWithinParent();g?(d.splice(e,0,h),this.remove()):d.splice(e,1,h);C(b)&&ge(b,c,e,f-1);return h}mergeWithSibling(a){var b=a===this.getPreviousSibling();b||
a===this.getNextSibling()||t(42);var c=this.__key;let d=a.__key,e=this.__text,f=e.length;gc()===d&&H(c);let g=u();if(C(g)){let h=g.anchor,k=g.focus;null!==h&&h.key===d&&(Ae(h,b,c,a,f),g.dirty=!0);null!==k&&k.key===d&&(Ae(k,b,c,a,f),g.dirty=!0)}c=a.__text;this.setTextContent(b?c+e:e+c);b=this.getWritable();a.remove();return b}isTextEntity(){return!1}}function ye(a){return{forChild:Be(a.style),node:null}}
function we(a){return{forChild:Be(a.style,"normal"===a.style.fontWeight?void 0:"bold"),node:null}}let Ce=new WeakMap;
function ve(a){null===a.parentElement&&t(43);for(var b=a.textContent||"",c,d=a.parentNode,e=[a];null!==d&&void 0===(c=Ce.get(d))&&!("PRE"===d.nodeName||1===d.nodeType&&void 0!==d.style&&void 0!==d.style.whiteSpace&&d.style.whiteSpace.startsWith("pre"));)e.push(d),d=d.parentNode;c=void 0===c?d:c;for(d=0;d<e.length;d++)Ce.set(e[d],c);if(null!==c){b=b.split(/(\r?\n|\t)/);a=[];e=b.length;for(c=0;c<e;c++)d=b[c],"\n"===d||"\r\n"===d?a.push(oe()):"\t"===d?a.push(De()):""!==d&&a.push(K(d));return{node:a}}b=
b.replace(/\r/g,"").replace(/[ \t\n]+/g," ");if(""===b)return{node:null};if(" "===b[0]){e=a;for(c=!0;null!==e&&null!==(e=Ne(e,!1));)if(d=e.textContent||"",0<d.length){/[ \t\n]$/.test(d)&&(b=b.slice(1));c=!1;break}c&&(b=b.slice(1))}if(" "===b[b.length-1]){for(e=!0;null!==a&&null!==(a=Ne(a,!0));)if(0<(a.textContent||"").replace(/^( |\t|\r?\n)+/,"").length){e=!1;break}e&&(b=b.slice(0,b.length-1))}return""===b?{node:null}:{node:K(b)}}
function Ne(a,b){for(;;){for(var c=void 0;null===(c=b?a.nextSibling:a.previousSibling);)if(a=a.parentElement,null===a)return null;a=c;if(1===a.nodeType&&(c=a.style.display,""===c&&!Ic(a)||""!==c&&!c.startsWith("inline")))return null;for(;null!==(c=b?a.firstChild:a.lastChild);)a=c;if(3===a.nodeType)return a;if("BR"===a.nodeName)return null}}let Oe={code:"code",em:"italic",i:"italic",s:"strikethrough",strong:"bold",sub:"subscript",sup:"superscript",u:"underline"};
function xe(a){let b=Oe[a.nodeName.toLowerCase()];return void 0===b?{node:null}:{forChild:Be(a.style,b),node:null}}function K(a=""){return Dc(new ue(a))}function B(a){return a instanceof ue}
function Be(a,b){let c=a.fontWeight,d=a.textDecoration.split(" "),e="700"===c||"bold"===c,f=d.includes("line-through"),g="italic"===a.fontStyle,h=d.includes("underline"),k=a.verticalAlign;return l=>{if(!B(l))return l;e&&!l.hasFormat("bold")&&l.toggleFormat("bold");f&&!l.hasFormat("strikethrough")&&l.toggleFormat("strikethrough");g&&!l.hasFormat("italic")&&l.toggleFormat("italic");h&&!l.hasFormat("underline")&&l.toggleFormat("underline");"sub"!==k||l.hasFormat("subscript")||l.toggleFormat("subscript");
"super"!==k||l.hasFormat("superscript")||l.toggleFormat("superscript");b&&!l.hasFormat(b)&&l.toggleFormat(b);return l}}
class Pe extends ue{static getType(){return"tab"}static clone(a){let b=new Pe(a.__key);b.__text=a.__text;b.__format=a.__format;b.__style=a.__style;return b}constructor(a){super("\t",a);this.__detail=2}static importDOM(){return null}static importJSON(a){let b=De();b.setFormat(a.format);b.setStyle(a.style);return b}exportJSON(){return{...super.exportJSON(),type:"tab",version:1}}setTextContent(){t(36)}setDetail(){t(37)}setMode(){t(38)}canInsertTextBefore(){return!1}canInsertTextAfter(){return!1}}
function De(){return Dc(new Pe)}function Qe(a){return a instanceof Pe}
class Re{constructor(a,b,c){this._selection=null;this.key=a;this.offset=b;this.type=c}is(a){return this.key===a.key&&this.offset===a.offset&&this.type===a.type}isBefore(a){let b=this.getNode(),c=a.getNode(),d=this.offset;a=a.offset;if(E(b)){var e=b.getDescendantByIndex(d);b=null!=e?e:b}E(c)&&(e=c.getDescendantByIndex(a),c=null!=e?e:c);return b===c?d<a:b.isBefore(c)}getNode(){let a=I(this.key);null===a&&t(12);return a}set(a,b,c){let d=this._selection,e=this.key;this.key=a;this.offset=b;this.type=c;
hc()||(gc()===e&&H(a),null!==d&&(d.setCachedNodes(null),d.dirty=!0))}}function Se(a,b,c){return new Re(a,b,c)}function Te(a,b){let c=b.__key,d=a.offset,e="element";if(B(b))e="text",b=b.getTextContentSize(),d>b&&(d=b);else if(!E(b)){var f=b.getNextSibling();if(B(f))c=f.__key,d=0,e="text";else if(f=b.getParent())c=f.__key,d=b.getIndexWithinParent()+1}a.set(c,d,e)}function ie(a,b){if(E(b)){let c=b.getLastDescendant();E(c)||B(c)?Te(a,c):Te(a,b)}else Te(a,b)}
function Ue(a,b,c,d){a.key=b;a.offset=c;a.type=d}
class Ve{constructor(a){this._cachedNodes=null;this._nodes=a;this.dirty=!1}getCachedNodes(){return this._cachedNodes}setCachedNodes(a){this._cachedNodes=a}is(a){if(!$d(a))return!1;let b=this._nodes,c=a._nodes;return b.size===c.size&&Array.from(b).every(d=>c.has(d))}isCollapsed(){return!1}isBackward(){return!1}getStartEndPoints(){return null}add(a){this.dirty=!0;this._nodes.add(a);this._cachedNodes=null}delete(a){this.dirty=!0;this._nodes.delete(a);this._cachedNodes=null}clear(){this.dirty=!0;this._nodes.clear();
this._cachedNodes=null}has(a){return this._nodes.has(a)}clone(){return new Ve(new Set(this._nodes))}extract(){return this.getNodes()}insertRawText(){}insertText(){}insertNodes(a){let b=this.getNodes(),c=b.length;var d=b[c-1];if(B(d))d=d.select();else{let e=d.getIndexWithinParent()+1;d=d.getParentOrThrow().select(e,e)}d.insertNodes(a);for(a=0;a<c;a++)b[a].remove()}getNodes(){var a=this._cachedNodes;if(null!==a)return a;var b=this._nodes;a=[];for(let c of b)b=I(c),null!==b&&a.push(b);hc()||(this._cachedNodes=
a);return a}getTextContent(){let a=this.getNodes(),b="";for(let c=0;c<a.length;c++)b+=a[c].getTextContent();return b}}function C(a){return a instanceof We}
class We{constructor(a,b,c,d){this.anchor=a;this.focus=b;a._selection=this;b._selection=this;this._cachedNodes=null;this.format=c;this.style=d;this.dirty=!1}getCachedNodes(){return this._cachedNodes}setCachedNodes(a){this._cachedNodes=a}is(a){return C(a)?this.anchor.is(a.anchor)&&this.focus.is(a.focus)&&this.format===a.format&&this.style===a.style:!1}isCollapsed(){return this.anchor.is(this.focus)}getNodes(){var a=this._cachedNodes;if(null!==a)return a;a=this.anchor;var b=this.focus,c=a.isBefore(b),
d=c?a:b;c=c?b:a;a=d.getNode();b=c.getNode();let e=d.offset;d=c.offset;E(a)&&(c=a.getDescendantByIndex(e),a=null!=c?c:a);E(b)&&(c=b.getDescendantByIndex(d),null!==c&&c!==a&&b.getChildAtIndex(d)===c&&(c=c.getPreviousSibling()),b=null!=c?c:b);a=a.is(b)?E(a)&&0<a.getChildrenSize()?[]:[a]:a.getNodesBetween(b);hc()||(this._cachedNodes=a);return a}setTextNodeRange(a,b,c,d){Ue(this.anchor,a.__key,b,"text");Ue(this.focus,c.__key,d,"text");this._cachedNodes=null;this.dirty=!0}getTextContent(){let a=this.getNodes();
if(0===a.length)return"";let b=a[0],c=a[a.length-1],d=this.anchor,e=this.focus,f=d.isBefore(e),[g,h]=Xe(this),k="",l=!0;for(let p=0;p<a.length;p++){let q=a[p];if(E(q)&&!q.isInline())l||(k+="\n"),l=q.isEmpty()?!1:!0;else if(l=!1,B(q)){let m=q.getTextContent();if(q===b)if(q===c){if("element"!==d.type||"element"!==e.type||e.offset===d.offset)m=g<h?m.slice(g,h):m.slice(h,g)}else m=f?m.slice(g):m.slice(h);else q===c&&(m=f?m.slice(0,h):m.slice(0,g));k+=m}else!y(q)&&!Kc(q)||q===c&&this.isCollapsed()||(k+=
q.getTextContent())}return k}applyDOMRange(a){let b=F(),c=b.getEditorState()._selection;a=Ye(a.startContainer,a.startOffset,a.endContainer,a.endOffset,b,c);if(null!==a){var [d,e]=a;Ue(this.anchor,d.key,d.offset,d.type);Ue(this.focus,e.key,e.offset,e.type);this._cachedNodes=null}}clone(){let a=this.anchor,b=this.focus;return new We(Se(a.key,a.offset,a.type),Se(b.key,b.offset,b.type),this.format,this.style)}toggleFormat(a){this.format=ac(this.format,a,null);this.dirty=!0}setStyle(a){this.style=a;this.dirty=
!0}hasFormat(a){return 0!==(this.format&ib[a])}insertRawText(a){a=a.split(/(\r?\n|\t)/);let b=[],c=a.length;for(let d=0;d<c;d++){let e=a[d];"\n"===e||"\r\n"===e?b.push(oe()):"\t"===e?b.push(De()):b.push(K(e))}this.insertNodes(b)}insertText(a){var b=this.anchor,c=this.focus,d=this.format,e=this.style,f=b,g=c;!this.isCollapsed()&&c.isBefore(b)&&(f=c,g=b);if("element"===f.type){b=f;c=g;var h=b.getNode(),k=h.getChildAtIndex(b.offset),l=K(),p=L(h)?je().append(l):l;l.setFormat(d);l.setStyle(e);null===k?
h.append(p):k.insertBefore(p);b.is(c)&&c.set(l.__key,0,"text");b.set(l.__key,0,"text")}c=f.offset;p=g.offset;h=this.getNodes();k=h.length;b=h[0];B(b)||t(13);l=b.getTextContent().length;var q=b.getParentOrThrow(),m=h[k-1];1===k&&"element"===g.type&&(p=l,g.set(f.key,p,"text"));if(this.isCollapsed()&&c===l&&(b.isSegmented()||b.isToken()||!b.canInsertTextAfter()||!q.canInsertTextAfter()&&null===b.getNextSibling())){if(f=b.getNextSibling(),B(f)&&f.canInsertTextBefore()&&!Zb(f)||(f=K(),f.setFormat(d),f.setStyle(e),
q.canInsertTextAfter()?b.insertAfter(f):q.insertAfter(f)),f.select(0,0),b=f,""!==a){this.insertText(a);return}}else if(this.isCollapsed()&&0===c&&(b.isSegmented()||b.isToken()||!b.canInsertTextBefore()||!q.canInsertTextBefore()&&null===b.getPreviousSibling())){f=b.getPreviousSibling();if(!B(f)||Zb(f))f=K(),f.setFormat(d),q.canInsertTextBefore()?b.insertBefore(f):q.insertBefore(f);f.select();b=f;if(""!==a){this.insertText(a);return}}else if(b.isSegmented()&&c!==l)f=K(b.getTextContent()),f.setFormat(d),
b.replace(f),b=f;else if(!(this.isCollapsed()||""===a||(f=m.getParent(),q.canInsertTextBefore()&&q.canInsertTextAfter()&&(!E(f)||f.canInsertTextBefore()&&f.canInsertTextAfter())))){this.insertText("");Ze(this.anchor,this.focus,null);this.insertText(a);return}if(1===k)if(b.isToken())a=K(a),a.select(),b.replace(a);else{h=b.getFormat();k=b.getStyle();if(c===p&&(h!==d||k!==e))if(""===b.getTextContent())b.setFormat(d),b.setStyle(e);else{h=K(a);h.setFormat(d);h.setStyle(e);h.select();0===c?b.insertBefore(h,
!1):([b]=b.splitText(c),b.insertAfter(h,!1));h.isComposing()&&"text"===this.anchor.type&&(this.anchor.offset-=a.length);return}else if(Qe(b)){a=K(a);a.setFormat(d);a.setStyle(e);a.select();b.replace(a);return}b=b.spliceText(c,p-c,a,!0);""===b.getTextContent()?b.remove():"text"===this.anchor.type&&(b.isComposing()?this.anchor.offset-=a.length:(this.format=h,this.style=k))}else{d=new Set([...b.getParentKeys(),...m.getParentKeys()]);q=E(b)?b:b.getParentOrThrow();e=E(m)?m:m.getParentOrThrow();f=m;if(!q.is(e)&&
e.isInline()){do f=e,e=e.getParentOrThrow();while(e.isInline())}if("text"===g.type&&(0!==p||""===m.getTextContent())||"element"===g.type&&m.getIndexWithinParent()<p)if(B(m)&&!m.isToken()&&p!==m.getTextContentSize()){if(m.isSegmented()){var r=K(m.getTextContent());m.replace(r);m=r}L(g.getNode())||"text"!==g.type||(m=m.spliceText(0,p,""));d.add(m.__key)}else g=m.getParentOrThrow(),g.canBeEmpty()||1!==g.getChildrenSize()?m.remove():g.remove();else d.add(m.__key);g=e.getChildren();p=new Set(h);m=q.is(e);
q=q.isInline()&&null===b.getNextSibling()?q:b;for(r=g.length-1;0<=r;r--){let w=g[r];if(w.is(b)||E(w)&&w.isParentOf(b))break;w.isAttached()&&(!p.has(w)||w.is(f)?m||q.insertAfter(w,!1):w.remove())}if(!m)for(g=e,e=null;null!==g;){p=g.getChildren();m=p.length;if(0===m||p[m-1].is(e))d.delete(g.__key),e=g;g=g.getParent()}b.isToken()?c===l?b.select():(a=K(a),a.select(),b.replace(a)):(b=b.spliceText(c,l-c,a,!0),""===b.getTextContent()?b.remove():b.isComposing()&&"text"===this.anchor.type&&(this.anchor.offset-=
a.length));for(a=1;a<k;a++)b=h[a],d.has(b.__key)||b.remove()}}removeText(){this.insertText("")}formatText(a){if(this.isCollapsed())this.toggleFormat(a),H(null);else{var b=this.getNodes(),c=[];for(var d of b)B(d)&&c.push(d);var e=c.length;if(0===e)this.toggleFormat(a),H(null);else{d=this.anchor;var f=this.focus,g=this.isBackward();b=g?f:d;d=g?d:f;var h=0,k=c[0];f="element"===b.type?0:b.offset;"text"===b.type&&f===k.getTextContentSize()&&(h=1,k=c[1],f=0);if(null!=k){g=k.getFormatFlags(a,null);var l=
e-1,p=c[l];e="text"===d.type?d.offset:p.getTextContentSize();if(k.is(p))f!==e&&(Zb(k)||0===f&&e===k.getTextContentSize()?k.setFormat(g):(a=k.splitText(f,e),a=0===f?a[0]:a[1],a.setFormat(g),"text"===b.type&&b.set(a.__key,0,"text"),"text"===d.type&&d.set(a.__key,e-f,"text")),this.format=g);else{0===f||Zb(k)||([,k]=k.splitText(f),f=0);k.setFormat(g);var q=p.getFormatFlags(a,g);0<e&&(e===p.getTextContentSize()||Zb(p)||([p]=p.splitText(e)),p.setFormat(q));for(h+=1;h<l;h++){let m=c[h],r=m.getFormatFlags(a,
q);m.setFormat(r)}"text"===b.type&&b.set(k.__key,f,"text");"text"===d.type&&d.set(p.__key,e,"text");this.format=g|q}}}}}insertNodes(a){if(0!==a.length){if("root"===this.anchor.key){this.insertParagraph();var b=u();C(b)||t(14);return b.insertNodes(a)}b=this.isBackward()?this.focus:this.anchor;var c=Lc(b.getNode(),Jc);b=a[a.length-1];if("__language"in c&&E(c))if("__language"in a[0])this.insertText(a[0].getTextContent());else{var d=$e(this);c.splice(d,0,a);b.selectEnd()}else if(a.some(g=>(E(g)||y(g))&&
!g.isInline())){b=af(a);a=b.getLastDescendant();var e=b.getChildren();b=E(c)&&c.isEmpty()?null:this.insertParagraph();d=e[e.length-1];var f=e[0];(g=>E(g)&&Jc(g)&&!g.isEmpty()&&E(c)&&(!c.isEmpty()||"__value"in c&&"__checked"in c))(f)&&(E(c)||t(15),c.append(...f.getChildren()),f=e[1]);f&&ke(c,f);e=Lc(a,Jc);b&&E(e)&&("__value"in b&&"__checked"in b||Jc(d))&&(e.append(...b.getChildren()),b.remove());E(c)&&c.isEmpty()&&c.remove();a.selectEnd();a=E(c)?c.getLastChild():null;Kc(a)&&e!==c&&a.remove()}else E(c)||
t(15),d=$e(this),c.splice(d,0,a),b.selectEnd()}}insertParagraph(){if("root"===this.anchor.key){var a=je();J().splice(this.anchor.offset,0,[a]);a.select();return a}var b=$e(this);a=Lc(this.anchor.getNode(),Jc);E(a)||t(16);b=(b=a.getChildAtIndex(b))?[b,...b.getNextSiblings()]:[];return(a=a.insertNewAfter(this,!1))?(a.append(...b),a.selectStart(),a):null}insertLineBreak(a){var b=oe();this.insertNodes([b]);a&&(a=b.getParentOrThrow(),b=b.getIndexWithinParent(),a.select(b,b))}extract(){var a=this.getNodes(),
b=a.length,c=b-1,d=this.anchor;let e=this.focus;var f=a[0];let g=a[c],[h,k]=Xe(this);if(0===b)return[];if(1===b)return B(f)&&!this.isCollapsed()?(a=h>k?k:h,c=f.splitText(a,h>k?h:k),a=0===a?c[0]:c[1],null!=a?[a]:[]):[f];b=d.isBefore(e);B(f)&&(d=b?h:k,d===f.getTextContentSize()?a.shift():0!==d&&([,f]=f.splitText(d),a[0]=f));B(g)&&(f=g.getTextContent().length,b=b?k:h,0===b?a.pop():b!==f&&([g]=g.splitText(b),a[c]=g));return a}modify(a,b,c){var d=this.focus,e=this.anchor,f="move"===a,g=wc(d,b);if(y(g)&&
!g.isIsolated())f&&g.isKeyboardSelectable()?(b=bf(),b.add(g.__key),Db(b)):(a=b?g.getPreviousSibling():g.getNextSibling(),B(a)?(g=a.__key,b=b?a.getTextContent().length:0,d.set(g,b,"text"),f&&e.set(g,b,"text")):(c=g.getParentOrThrow(),E(a)?(c=a.__key,g=b?a.getChildrenSize():0):(g=g.getIndexWithinParent(),c=c.__key,b||g++),d.set(c,g,"element"),f&&e.set(c,g,"element")));else if(e=F(),d=Ab(e._window)){var h=e._blockCursorElement,k=e._rootElement;null===k||null===h||!E(g)||g.isInline()||g.canBeEmpty()||
Gc(h,e,k);d.modify(a,b?"backward":"forward",c);if(0<d.rangeCount&&(g=d.getRangeAt(0),e=this.anchor.getNode(),e=L(e)?e:Ac(e),this.applyDOMRange(g),this.dirty=!0,!f)){f=this.getNodes();a=[];c=!1;for(h=0;h<f.length;h++)k=f[h],zc(k,e)?a.push(k):c=!0;c&&0<a.length&&(b?(b=a[0],E(b)?b.selectStart():b.getParentOrThrow().selectStart()):(b=a[a.length-1],E(b)?b.selectEnd():b.getParentOrThrow().selectEnd()));if(d.anchorNode!==g.startContainer||d.anchorOffset!==g.startOffset)b=this.focus,f=this.anchor,d=f.key,
g=f.offset,e=f.type,Ue(f,b.key,b.offset,b.type),Ue(b,d,g,e),this._cachedNodes=null}}}forwardDeletion(a,b,c){return!c&&("element"===a.type&&E(b)&&a.offset===b.getChildrenSize()||"text"===a.type&&a.offset===b.getTextContentSize())&&(a=b.getParent(),b=b.getNextSibling()||(null===a?null:a.getNextSibling()),E(b)&&b.isShadowRoot())?!0:!1}deleteCharacter(a){let b=this.isCollapsed();if(this.isCollapsed()){var c=this.anchor,d=c.getNode();if(this.forwardDeletion(c,d,a))return;var e=this.focus,f=wc(e,a);if(y(f)&&
!f.isIsolated()){f.isKeyboardSelectable()&&E(d)&&0===d.getChildrenSize()?(d.remove(),a=bf(),a.add(f.__key),Db(a)):(f.remove(),F().dispatchCommand(aa,void 0));return}if(!a&&E(f)&&E(d)&&d.isEmpty()){d.remove();f.selectStart();return}this.modify("extend",a,"character");if(!this.isCollapsed()){f="text"===e.type?e.getNode():null;d="text"===c.type?c.getNode():null;if(null!==f&&f.isSegmented()){if(c=e.offset,e=f.getTextContentSize(),f.is(d)||a&&c!==e||!a&&0!==c){cf(f,a,c);return}}else if(null!==d&&d.isSegmented()&&
(c=c.offset,e=d.getTextContentSize(),d.is(f)||a&&0!==c||!a&&c!==e)){cf(d,a,c);return}d=this.anchor;f=this.focus;c=d.getNode();e=f.getNode();if(c===e&&"text"===d.type&&"text"===f.type){var g=d.offset,h=f.offset;let k=g<h;e=k?g:h;h=k?h:g;g=h-1;e!==g&&(c=c.getTextContent().slice(e,h),mc(c)||(a?f.offset=g:d.offset=g))}}else if(a&&0===c.offset&&("element"===c.type?c.getNode():c.getNode().getParentOrThrow()).collapseAtStart(this))return}this.removeText();a&&!b&&this.isCollapsed()&&"element"===this.anchor.type&&
0===this.anchor.offset&&(a=this.anchor.getNode(),a.isEmpty()&&L(a.getParent())&&0===a.getIndexWithinParent()&&a.collapseAtStart(this))}deleteLine(a){if(this.isCollapsed()){let b="element"===this.anchor.type;b&&this.insertText(" ");this.modify("extend",a,"lineboundary");0===(a?this.focus:this.anchor).offset&&this.modify("extend",a,"character");b&&(a=a?this.anchor:this.focus,a.set(a.key,a.offset+1,a.type))}this.removeText()}deleteWord(a){if(this.isCollapsed()){let b=this.anchor,c=b.getNode();if(this.forwardDeletion(b,
c,a))return;this.modify("extend",a,"word")}this.removeText()}isBackward(){return this.focus.isBefore(this.anchor)}getStartEndPoints(){return[this.anchor,this.focus]}}function $d(a){return a instanceof Ve}function df(a){let b=a.offset;if("text"===a.type)return b;a=a.getNode();return b===a.getChildrenSize()?a.getTextContent().length:0}
function Xe(a){a=a.getStartEndPoints();if(null===a)return[0,0];let [b,c]=a;return"element"===b.type&&"element"===c.type&&b.key===c.key&&b.offset===c.offset?[0,0]:[df(b),df(c)]}function cf(a,b,c){let d=a.getTextContent().split(/(?=\s)/g),e=d.length,f=0,g=0;for(let h=0;h<e;h++){let k=d[h],l=h===e-1;g=f;f+=k.length;if(b&&f===c||f>c||l){d.splice(h,1);l&&(g=void 0);break}}b=d.join("").trim();""===b?a.remove():(a.setTextContent(b),a.select(g,g))}
function ef(a,b,c,d){let e=b;if(1===a.nodeType){var f=!1;var g=a.childNodes;var h=g.length;d=d._blockCursorElement;e===h&&(f=!0,e=h-1);let k=g[e];h=!1;k===d?(k=g[e+1],h=!0):null!==d&&(g=d.parentNode,a===g&&(g=Array.prototype.indexOf.call(g.children,d),b>g&&e--));g=lc(k);if(B(g))e=f?g.getTextContentSize():0;else{d=lc(a);if(null===d)return null;if(E(d)){e=Math.min(d.getChildrenSize(),e);a=d.getChildAtIndex(e);if(b=E(a))b=a.getParent(),b=null===c||null===b||!b.canBeEmpty()||b!==c.getNode();b&&(c=f?a.getLastDescendant():
a.getFirstDescendant(),null===c?d=a:(a=c,d=E(a)?a:a.getParentOrThrow()),e=0);B(a)?(g=a,d=null,e=f?a.getTextContentSize():0):a!==d&&f&&!h&&e++}else f=d.getIndexWithinParent(),e=0===b&&y(d)&&lc(a)===d?f:f+1,d=d.getParentOrThrow();if(E(d))return Se(d.__key,e,"element")}}else g=lc(a);return B(g)?Se(g.__key,e,"text"):null}
function ff(a,b,c){var d=a.offset,e=a.getNode();0===d?(d=e.getPreviousSibling(),e=e.getParent(),b)?(c||!b)&&null===d&&E(e)&&e.isInline()&&(b=e.getPreviousSibling(),B(b)&&(a.key=b.__key,a.offset=b.getTextContent().length)):E(d)&&!c&&d.isInline()?(a.key=d.__key,a.offset=d.getChildrenSize(),a.type="element"):B(d)&&(a.key=d.__key,a.offset=d.getTextContent().length):d===e.getTextContent().length&&(d=e.getNextSibling(),e=e.getParent(),b&&E(d)&&d.isInline()?(a.key=d.__key,a.offset=0,a.type="element"):(c||
b)&&null===d&&E(e)&&e.isInline()&&!e.canInsertTextAfter()&&(b=e.getNextSibling(),B(b)&&(a.key=b.__key,a.offset=0)))}function Ze(a,b,c){if("text"===a.type&&"text"===b.type){var d=a.isBefore(b);let e=a.is(b);ff(a,d,e);ff(b,!d,e);e&&(b.key=a.key,b.offset=a.offset,b.type=a.type);d=F();d.isComposing()&&d._compositionKey!==a.key&&C(c)&&(d=c.anchor,c=c.focus,Ue(a,d.key,d.offset,d.type),Ue(b,c.key,c.offset,c.type))}}
function Ye(a,b,c,d,e,f){if(null===a||null===c||!Qb(e,a,c))return null;b=ef(a,b,C(f)?f.anchor:null,e);if(null===b)return null;d=ef(c,d,C(f)?f.focus:null,e);if(null===d||"element"===b.type&&"element"===d.type&&(a=lc(a),c=lc(c),y(a)&&y(c)))return null;Ze(b,d,f);return[b,d]}function ze(a,b,c,d,e,f){let g=dc();a=new We(Se(a,b,e),Se(c,d,f),0,"");a.dirty=!0;return g._selection=a}function bf(){return new Ve(new Set)}
function gf(a){let b=a.getEditorState()._selection,c=Ab(a._window);return C(b)||null==b?Wd(b,c,a,null):b.clone()}
function Wd(a,b,c,d){var e=c._window;if(null===e)return null;var f=(e=d||e.event)?e.type:void 0;d="selectionchange"===f;e=!tb&&(d||"beforeinput"===f||"compositionstart"===f||"compositionend"===f||"click"===f&&e&&3===e.detail||"drop"===f||void 0===f);let g;if(!C(a)||e){if(null===b)return null;e=b.anchorNode;f=b.focusNode;g=b.anchorOffset;b=b.focusOffset;if(d&&C(a)&&!Qb(c,e,f))return a.clone()}else return a.clone();c=Ye(e,g,f,b,c,a);if(null===c)return null;let [h,k]=c;return new We(h,k,C(a)?a.format:
0,C(a)?a.style:"")}function u(){return dc()._selection}function qc(){return F()._editorState._selection}
function ge(a,b,c,d=1){var e=a.anchor,f=a.focus,g=e.getNode(),h=f.getNode();if(b.is(g)||b.is(h)){g=b.__key;if(a.isCollapsed()){if(b=e.offset,c<=b&&0<d||c<b&&0>d)c=Math.max(0,b+d),e.set(g,c,"element"),f.set(g,c,"element"),hf(a)}else{let l=a.isBackward();h=l?f:e;var k=h.getNode();e=l?e:f;f=e.getNode();b.is(k)&&(k=h.offset,(c<=k&&0<d||c<k&&0>d)&&h.set(g,Math.max(0,k+d),"element"));b.is(f)&&(b=e.offset,(c<=b&&0<d||c<b&&0>d)&&e.set(g,Math.max(0,b+d),"element"))}hf(a)}}
function hf(a){var b=a.anchor,c=b.offset;let d=a.focus;var e=d.offset,f=b.getNode(),g=d.getNode();if(a.isCollapsed())E(f)&&(g=f.getChildrenSize(),g=(e=c>=g)?f.getChildAtIndex(g-1):f.getChildAtIndex(c),B(g)&&(c=0,e&&(c=g.getTextContentSize()),b.set(g.__key,c,"text"),d.set(g.__key,c,"text")));else{if(E(f)){let h=f.getChildrenSize();c=(a=c>=h)?f.getChildAtIndex(h-1):f.getChildAtIndex(c);B(c)&&(f=0,a&&(f=c.getTextContentSize()),b.set(c.__key,f,"text"))}E(g)&&(c=g.getChildrenSize(),e=(b=e>=c)?g.getChildAtIndex(c-
1):g.getChildAtIndex(e),B(e)&&(g=0,b&&(g=e.getTextContentSize()),d.set(e.__key,g,"text")))}}function jf(a,b){b=b.getEditorState()._selection;a=a._selection;if(C(a)){var c=a.anchor;let d=a.focus,e;"text"===c.type&&(e=c.getNode(),e.selectionTransform(b,a));"text"===d.type&&(c=d.getNode(),e!==c&&c.selectionTransform(b,a))}}
function fe(a,b,c,d,e){let f=null,g=0,h=null;null!==d?(f=d.__key,B(d)?(g=d.getTextContentSize(),h="text"):E(d)&&(g=d.getChildrenSize(),h="element")):null!==e&&(f=e.__key,B(e)?h="text":E(e)&&(h="element"));null!==f&&null!==h?a.set(f,g,h):(g=b.getIndexWithinParent(),-1===g&&(g=c.getChildrenSize()),a.set(c.__key,g,"element"))}function Ae(a,b,c,d,e){"text"===a.type?(a.key=c,b||(a.offset+=e)):a.offset>d.getIndexWithinParent()&&--a.offset}
function $e(a){var b=a;a.isCollapsed()||b.removeText();a=u();C(a)&&(b=a);C(b)||t(17);a=b.anchor;b=a.getNode();for(a=a.offset;!Jc(b);)[b,a]=kf(b,a);return a}
function kf(a,b){var c=a.getParent();if(!c)return c=je(),J().append(c),c.select(),[J(),0];if(B(a)){var d=a.splitText(b);if(0===d.length)return[c,a.getIndexWithinParent()];a=0===b?0:1;a=d[0].getIndexWithinParent()+a;return[c,a]}if(!E(a)||0===b)return[c,a.getIndexWithinParent()];if(d=a.getChildAtIndex(b))b=new We(Se(a.__key,b,"element"),Se(a.__key,b,"element"),0,""),(b=a.insertNewAfter(b))&&b.append(d,...d.getNextSiblings());return[c,a.getIndexWithinParent()+1]}
function af(a){let b=je(),c=null;for(let d=0;d<a.length;d++){let e=a[d],f=Kc(e);if(f||y(e)&&e.isInline()||E(e)&&e.isInline()||B(e)||e.isParentRequired()){if(null===c&&(c=e.createParentElementNode(),b.append(c),f))continue;null!==c&&c.append(e)}else b.append(e),c=null}return b}let T=null,U=null,W=!1,lf=!1,cc=0,mf={characterData:!0,childList:!0,subtree:!0};function hc(){return W||null!==T&&T._readOnly}function G(){W&&t(5)}function dc(){null===T&&t(7);return T}function F(){null===U&&t(8);return U}
function nf(a,b,c){var d=b.__type;let e=a._nodes.get(d);void 0===e&&t(18,d);a=c.get(d);void 0===a&&(a=Array.from(e.transforms),c.set(d,a));c=a.length;for(d=0;d<c&&(a[d](b),b.isAttached());d++);}function of(a,b){b=b._dirtyLeaves;a=a._nodeMap;for(let c of b)b=a.get(c),B(b)&&b.isAttached()&&b.isSimpleText()&&!b.isUnmergeable()&&Kb(b)}
function pf(a,b){let c=b._dirtyLeaves,d=b._dirtyElements;a=a._nodeMap;let e=gc(),f=new Map;var g=c;let h=g.size;for(var k=d,l=k.size;0<h||0<l;){if(0<h){b._dirtyLeaves=new Set;for(let p of g)g=a.get(p),B(g)&&g.isAttached()&&g.isSimpleText()&&!g.isUnmergeable()&&Kb(g),void 0!==g&&void 0!==g&&g.__key!==e&&g.isAttached()&&nf(b,g,f),c.add(p);g=b._dirtyLeaves;h=g.size;if(0<h){cc++;continue}}b._dirtyLeaves=new Set;b._dirtyElements=new Map;for(let p of k)if(k=p[0],l=p[1],"root"===k||l)g=a.get(k),void 0!==
g&&void 0!==g&&g.__key!==e&&g.isAttached()&&nf(b,g,f),d.set(k,l);g=b._dirtyLeaves;h=g.size;k=b._dirtyElements;l=k.size;cc++}b._dirtyLeaves=c;b._dirtyElements=d}function qf(a,b){var c=a.type,d=b.get(c);void 0===d&&t(9,c);c=d.klass;a.type!==c.getType()&&t(10,c.name);c=c.importJSON(a);a=a.children;if(E(c)&&Array.isArray(a))for(d=0;d<a.length;d++){let e=qf(a[d],b);c.append(e)}return c}function rf(a,b){let c=T,d=W,e=U;T=a;W=!0;U=null;try{return b()}finally{T=c,W=d,U=e}}
function sf(a,b){let c=a._pendingEditorState,d=a._rootElement,e=a._headless||null===d;if(null!==c){var f=a._editorState,g=f._selection,h=c._selection,k=0!==a._dirtyType,l=T,p=W,q=U,m=a._updating,r=a._observer,w=null;a._pendingEditorState=null;a._editorState=c;if(!e&&k&&null!==r){U=a;T=c;W=!1;a._updating=!0;try{let D=a._dirtyType,P=a._dirtyElements,Q=a._dirtyLeaves;r.disconnect();var A=D,x=P,z=Q;N=Oc=M="";Rc=2===A;Uc=null;R=a;Pc=a._config;Qc=a._nodes;Tc=R._listeners.mutation;Vc=x;ed=z;fd=f._nodeMap;
gd=c._nodeMap;Sc=c._readOnly;hd=new Map(a._keyToDOMMap);let ka=new Map;id=ka;wd("root",null);id=hd=Pc=gd=fd=ed=Vc=Qc=R=void 0;w=ka}catch(D){D instanceof Error&&a._onError(D);if(lf)throw D;tf(a,null,d,c);Gb(a);a._dirtyType=2;lf=!0;sf(a,f);lf=!1;return}finally{r.observe(d,mf),a._updating=m,T=l,W=p,U=q}}c._readOnly||(c._readOnly=!0);var ba=a._dirtyLeaves,ha=a._dirtyElements,Ya=a._normalizedNodes,ma=a._updateTags,Wc=a._deferred;k&&(a._dirtyType=0,a._cloneNotNeeded.clear(),a._dirtyLeaves=new Set,a._dirtyElements=
new Map,a._normalizedNodes=new Set,a._updateTags=new Set);var Ee=a._decorators,Tb=a._pendingDecorators||Ee,Ff=c._nodeMap,Xc;for(Xc in Tb)Ff.has(Xc)||(Tb===Ee&&(Tb=ic(a)),delete Tb[Xc]);var la=e?null:Ab(a._window);if(a._editable&&null!==la&&(k||null===h||h.dirty)){U=a;T=c;try{null!==r&&r.disconnect();if(k||null===h||h.dirty){let D=a._blockCursorElement;null!==D&&Gc(D,a,d);a:{let P=la.anchorNode,Q=la.focusNode,ka=la.anchorOffset,mb=la.focusOffset,X=document.activeElement;if(!(ma.has("collaboration")&&
X!==d||null!==X&&Pb(X)))if(C(h)){var nb=h.anchor,Yc=h.focus,Fe=nb.key,Gf=Yc.key,Ge=yc(a,Fe),He=yc(a,Gf),Ub=nb.offset,Ie=Yc.offset,Zc=h.format,$c=h.style,Je=h.isCollapsed(),ob=Ge,Vb=He,ad=!1;if("text"===nb.type){ob=$b(Ge);let Y=nb.getNode();ad=Y.getFormat()!==Zc||Y.getStyle()!==$c}else C(g)&&"text"===g.anchor.type&&(ad=!0);"text"===Yc.type&&(Vb=$b(He));if(null!==ob&&null!==Vb){if(Je&&(null===g||ad||C(g)&&(g.format!==Zc||g.style!==$c))){var Hf=performance.now();Rd=[Zc,$c,Ub,Fe,Hf]}if(ka===Ub&&mb===
Ie&&P===ob&&Q===Vb&&("Range"!==la.type||!Je)&&(null!==X&&d.contains(X)||d.focus({preventScroll:!0}),"element"!==nb.type))break a;try{la.setBaseAndExtent(ob,Ub,Vb,Ie)}catch(Y){}if(!ma.has("skip-scroll-into-view")&&h.isCollapsed()&&null!==d&&d===document.activeElement){let Y=h instanceof We&&"element"===h.anchor.type?ob.childNodes[Ub]||null:0<la.rangeCount?la.getRangeAt(0):null;if(null!==Y){let Z;if(Y instanceof Text){let V=document.createRange();V.selectNode(Y);Z=V.getBoundingClientRect()}else Z=Y.getBoundingClientRect();
let ya=d.ownerDocument,Fa=ya.defaultView;if(null!==Fa)for(var {top:bd,bottom:cd}=Z,Wb,Xb,qa=d;null!==qa;){let V=qa===ya.body;if(V)Wb=0,Xb=Hb(a).innerHeight;else{let Yb=qa.getBoundingClientRect();Wb=Yb.top;Xb=Yb.bottom}let Ga=0;bd<Wb?Ga=-(Wb-bd):cd>Xb&&(Ga=cd-Xb);if(0!==Ga)if(V)Fa.scrollBy(0,Ga);else{let Yb=qa.scrollTop;qa.scrollTop+=Ga;let Ke=qa.scrollTop-Yb;bd-=Ke;cd-=Ke}if(V)break;qa=Sb(qa)}}}Nd=!0}}else null!==g&&Qb(a,P,Q)&&la.removeAllRanges()}}a:{let D=a._blockCursorElement;if(C(h)&&h.isCollapsed()&&
"element"===h.anchor.type&&d.contains(document.activeElement)){let P=h.anchor,Q=P.getNode(),ka=P.offset,mb=Q.getChildrenSize(),X=!1,Y=null;if(ka===mb){let Z=Q.getChildAtIndex(ka-1);Fc(Z)&&(X=!0)}else{let Z=Q.getChildAtIndex(ka);if(Fc(Z)){let ya=Z.getPreviousSibling();if(null===ya||Fc(ya))X=!0,Y=a.getElementByKey(Z.__key)}}if(X){let Z=a.getElementByKey(Q.__key);if(null===D){let ya=a._config.theme,Fa=document.createElement("div");Fa.contentEditable="false";Fa.setAttribute("data-lexical-cursor","true");
let V=ya.blockCursor;if(void 0!==V){if("string"===typeof V){let Ga=sb(V);V=ya.blockCursor=Ga}void 0!==V&&Fa.classList.add(...V)}a._blockCursorElement=D=Fa}d.style.caretColor="transparent";null===Y?Z.appendChild(D):Z.insertBefore(D,Y);break a}}null!==D&&Gc(D,a,d)}null!==r&&r.observe(d,mf)}finally{U=q,T=l}}if(null!==w){var If=w;let D=Array.from(a._listeners.mutation),P=D.length;for(let Q=0;Q<P;Q++){let [ka,mb]=D[Q],X=If.get(mb);void 0!==X&&ka(X,{dirtyLeaves:ba,prevEditorState:f,updateTags:ma})}}C(h)||
null===h||null!==g&&g.is(h)||a.dispatchCommand(aa,void 0);var dd=a._pendingDecorators;null!==dd&&(a._decorators=dd,a._pendingDecorators=null,uf("decorator",a,!0,dd));var Jf=jc(b||f),Le=jc(c);Jf!==Le&&uf("textcontent",a,!0,Le);uf("update",a,!0,{dirtyElements:ha,dirtyLeaves:ba,editorState:c,normalizedNodes:Ya,prevEditorState:b||f,tags:ma});a._deferred=[];if(0!==Wc.length){let D=a._updating;a._updating=!0;try{for(let P=0;P<Wc.length;P++)Wc[P]()}finally{a._updating=D}}var Me=a._updates;if(0!==Me.length){let D=
Me.shift();if(D){let [P,Q]=D;vf(a,P,Q)}}}}function uf(a,b,c,...d){let e=b._updating;b._updating=c;try{let f=Array.from(b._listeners[a]);for(a=0;a<f.length;a++)f[a].apply(null,d)}finally{b._updating=e}}
function S(a,b,c){if(!1===a._updating||U!==a){let f=!1;a.update(()=>{f=S(a,b,c)});return f}let d=nc(a);for(let f=4;0<=f;f--)for(let g=0;g<d.length;g++){var e=d[g]._commands.get(b);if(void 0!==e&&(e=e[f],void 0!==e)){e=Array.from(e);let h=e.length;for(let k=0;k<h;k++)if(!0===e[k](c,a))return!0}}return!1}
function wf(a,b){let c=a._updates;for(b=b||!1;0!==c.length;){var d=c.shift();if(d){let [e,f]=d,g;void 0!==f&&(d=f.onUpdate,g=f.tag,f.skipTransforms&&(b=!0),d&&a._deferred.push(d),g&&a._updateTags.add(g));e()}}return b}
function vf(a,b,c){let d=a._updateTags;var e,f=e=!1;if(void 0!==c){var g=c.onUpdate;e=c.tag;null!=e&&d.add(e);e=c.skipTransforms||!1;f=c.discrete||!1}g&&a._deferred.push(g);c=a._editorState;g=a._pendingEditorState;let h=!1;if(null===g||g._readOnly)g=a._pendingEditorState=new xf(new Map((g||c)._nodeMap)),h=!0;g._flushSync=f;f=T;let k=W,l=U,p=a._updating;T=g;W=!1;a._updating=!0;U=a;try{h&&(a._headless?null!==c._selection&&(g._selection=c._selection.clone()):g._selection=gf(a));let q=a._compositionKey;
b();e=wf(a,e);jf(g,a);0!==a._dirtyType&&(e?of(g,a):pf(g,a),wf(a),Nc(c,g,a._dirtyLeaves,a._dirtyElements));q!==a._compositionKey&&(g._flushSync=!0);let m=g._selection;if(C(m)){let r=g._nodeMap,w=m.focus.key;void 0!==r.get(m.anchor.key)&&void 0!==r.get(w)||t(11)}else $d(m)&&0===m._nodes.size&&(g._selection=null)}catch(q){q instanceof Error&&a._onError(q);a._pendingEditorState=c;a._dirtyType=2;a._cloneNotNeeded.clear();a._dirtyLeaves=new Set;a._dirtyElements.clear();sf(a);return}finally{T=f,W=k,U=l,
a._updating=p,cc=0}0!==a._dirtyType||yf(g,a)?g._flushSync?(g._flushSync=!1,sf(a)):h&&Ob(()=>{sf(a)}):(g._flushSync=!1,h&&(d.clear(),a._deferred=[],a._pendingEditorState=null))}function v(a,b,c){a._updating?a._updates.push([b,c]):vf(a,b,c)}
class zf extends he{constructor(a){super(a);this.__last=this.__first=null;this.__indent=this.__format=this.__size=0;this.__dir=null}getFormat(){return this.getLatest().__format}getFormatType(){let a=this.getFormat();return lb[a]||""}getIndent(){return this.getLatest().__indent}getChildren(){let a=[],b=this.getFirstChild();for(;null!==b;)a.push(b),b=b.getNextSibling();return a}getChildrenKeys(){let a=[],b=this.getFirstChild();for(;null!==b;)a.push(b.__key),b=b.getNextSibling();return a}getChildrenSize(){return this.getLatest().__size}isEmpty(){return 0===
this.getChildrenSize()}isDirty(){let a=F()._dirtyElements;return null!==a&&a.has(this.__key)}isLastChild(){let a=this.getLatest(),b=this.getParentOrThrow().getLastChild();return null!==b&&b.is(a)}getAllTextNodes(){let a=[],b=this.getFirstChild();for(;null!==b;){B(b)&&a.push(b);if(E(b)){let c=b.getAllTextNodes();a.push(...c)}b=b.getNextSibling()}return a}getFirstDescendant(){let a=this.getFirstChild();for(;E(a);){let b=a.getFirstChild();if(null===b)break;a=b}return a}getLastDescendant(){let a=this.getLastChild();
for(;E(a);){let b=a.getLastChild();if(null===b)break;a=b}return a}getDescendantByIndex(a){let b=this.getChildren(),c=b.length;if(a>=c)return a=b[c-1],E(a)&&a.getLastDescendant()||a||null;a=b[a];return E(a)&&a.getFirstDescendant()||a||null}getFirstChild(){let a=this.getLatest().__first;return null===a?null:I(a)}getFirstChildOrThrow(){let a=this.getFirstChild();null===a&&t(32,this.__key);return a}getLastChild(){let a=this.getLatest().__last;return null===a?null:I(a)}getLastChildOrThrow(){let a=this.getLastChild();
null===a&&t(33,this.__key);return a}getChildAtIndex(a){var b=this.getChildrenSize();let c;if(a<b/2){c=this.getFirstChild();for(b=0;null!==c&&b<=a;){if(b===a)return c;c=c.getNextSibling();b++}return null}c=this.getLastChild();for(--b;null!==c&&b>=a;){if(b===a)return c;c=c.getPreviousSibling();b--}return null}getTextContent(){let a="",b=this.getChildren(),c=b.length;for(let d=0;d<c;d++){let e=b[d];a+=e.getTextContent();E(e)&&d!==c-1&&!e.isInline()&&(a+="\n\n")}return a}getTextContentSize(){let a=0,
b=this.getChildren(),c=b.length;for(let d=0;d<c;d++){let e=b[d];a+=e.getTextContentSize();E(e)&&d!==c-1&&!e.isInline()&&(a+=2)}return a}getDirection(){return this.getLatest().__dir}hasFormat(a){return""!==a?(a=kb[a],0!==(this.getFormat()&a)):!1}select(a,b){G();let c=u(),d=a,e=b;var f=this.getChildrenSize();if(!this.canBeEmpty())if(0===a&&0===b){if(a=this.getFirstChild(),B(a)||E(a))return a.select(0,0)}else if(!(void 0!==a&&a!==f||void 0!==b&&b!==f)&&(a=this.getLastChild(),B(a)||E(a)))return a.select();
void 0===d&&(d=f);void 0===e&&(e=f);f=this.__key;if(C(c))c.anchor.set(f,d,"element"),c.focus.set(f,e,"element"),c.dirty=!0;else return ze(f,d,f,e,"element","element");return c}selectStart(){let a=this.getFirstDescendant();return a?a.selectStart():this.select()}selectEnd(){let a=this.getLastDescendant();return a?a.selectEnd():this.select()}clear(){let a=this.getWritable();this.getChildren().forEach(b=>b.remove());return a}append(...a){return this.splice(this.getChildrenSize(),0,a)}setDirection(a){let b=
this.getWritable();b.__dir=a;return b}setFormat(a){this.getWritable().__format=""!==a?kb[a]:0;return this}setIndent(a){this.getWritable().__indent=a;return this}splice(a,b,c){let d=c.length,e=this.getChildrenSize(),f=this.getWritable(),g=f.__key;var h=[],k=[];let l=this.getChildAtIndex(a+b),p=null,q=e-b+d;if(0!==a)if(a===e)p=this.getLastChild();else{var m=this.getChildAtIndex(a);null!==m&&(p=m.getPreviousSibling())}if(0<b){var r=null===p?this.getFirstChild():p.getNextSibling();for(m=0;m<b;m++){null===
r&&t(34);var w=r.getNextSibling(),A=r.__key;r=r.getWritable();ec(r);k.push(A);r=w}}m=p;for(w=0;w<d;w++){A=c[w];null!==m&&A.is(m)&&(p=m=m.getPreviousSibling());r=A.getWritable();r.__parent===g&&q--;ec(r);let x=A.__key;null===m?(f.__first=x,r.__prev=null):(m=m.getWritable(),m.__next=x,r.__prev=m.__key);A.__key===g&&t(35);r.__parent=g;h.push(x);m=A}a+b===e?null!==m&&(m.getWritable().__next=null,f.__last=m.__key):null!==l&&(a=l.getWritable(),null!==m?(b=m.getWritable(),a.__prev=m.__key,b.__next=l.__key):
a.__prev=null);f.__size=q;if(k.length&&(a=u(),C(a))){k=new Set(k);h=new Set(h);let {anchor:x,focus:z}=a;Af(x,k,h)&&fe(x,x.getNode(),this,p,l);Af(z,k,h)&&fe(z,z.getNode(),this,p,l);0!==q||this.canBeEmpty()||Bc(this)||this.remove()}return f}exportJSON(){return{children:[],direction:this.getDirection(),format:this.getFormatType(),indent:this.getIndent(),type:"element",version:1}}insertNewAfter(){return null}canIndent(){return!0}collapseAtStart(){return!1}excludeFromCopy(){return!1}canReplaceWith(){return!0}canInsertAfter(){return!0}canBeEmpty(){return!0}canInsertTextBefore(){return!0}canInsertTextAfter(){return!0}isInline(){return!1}isShadowRoot(){return!1}canMergeWith(){return!1}extractWithChild(){return!1}}
function E(a){return a instanceof zf}function Af(a,b,c){for(a=a.getNode();a;){let d=a.__key;if(b.has(d)&&!c.has(d))return!0;a=a.getParent()}return!1}class Bf extends he{constructor(a){super(a)}decorate(){t(31)}isIsolated(){return!1}isInline(){return!0}isKeyboardSelectable(){return!0}}function y(a){return a instanceof Bf}
class Cf extends zf{static getType(){return"root"}static clone(){return new Cf}constructor(){super("root");this.__cachedText=null}getTopLevelElementOrThrow(){t(44)}getTextContent(){let a=this.__cachedText;return!hc()&&0!==F()._dirtyType||null===a?super.getTextContent():a}remove(){t(45)}replace(){t(46)}insertBefore(){t(47)}insertAfter(){t(48)}updateDOM(){return!1}append(...a){for(let b=0;b<a.length;b++){let c=a[b];E(c)||y(c)||t(49)}return super.append(...a)}static importJSON(a){let b=J();b.setFormat(a.format);
b.setIndent(a.indent);b.setDirection(a.direction);return b}exportJSON(){return{children:[],direction:this.getDirection(),format:this.getFormatType(),indent:this.getIndent(),type:"root",version:1}}collapseAtStart(){return!0}}function L(a){return a instanceof Cf}function yf(a,b){b=b.getEditorState()._selection;a=a._selection;if(null!==a){if(a.dirty||!a.is(b))return!0}else if(null!==b)return!0;return!1}function Df(){return new xf(new Map([["root",new Cf]]))}
function Ef(a){let b=a.exportJSON();var c=a.constructor;b.type!==c.getType()&&t(50,c.name);if(E(a)){let d=b.children;Array.isArray(d)||t(51,c.name);a=a.getChildren();for(c=0;c<a.length;c++){let e=Ef(a[c]);d.push(e)}}return b}
class xf{constructor(a,b){this._nodeMap=a;this._selection=b||null;this._readOnly=this._flushSync=!1}isEmpty(){return 1===this._nodeMap.size&&null===this._selection}read(a){return rf(this,a)}clone(a){a=new xf(this._nodeMap,void 0===a?this._selection:a);a._readOnly=!0;return a}toJSON(){return rf(this,()=>({root:Ef(J())}))}}class Kf extends zf{static getType(){return"artificial"}createDOM(){return document.createElement("div")}}
class Vd extends zf{constructor(a){super(a);this.__textFormat=0}static getType(){return"paragraph"}getTextFormat(){return this.getLatest().__textFormat}setTextFormat(a){let b=this.getWritable();b.__textFormat=a;return b}hasTextFormat(a){a=ib[a];return 0!==(this.getTextFormat()&a)}static clone(a){return new Vd(a.__key)}createDOM(a){let b=document.createElement("p");a=tc(a.theme,"paragraph");void 0!==a&&b.classList.add(...a);return b}updateDOM(){return!1}static importDOM(){return{p:()=>({conversion:Lf,
priority:0})}}exportDOM(a){({element:a}=super.exportDOM(a));if(a&&Hc(a)){this.isEmpty()&&a.append(document.createElement("br"));var b=this.getFormatType();a.style.textAlign=b;if(b=this.getDirection())a.dir=b;b=this.getIndent();0<b&&(a.style.textIndent=`${20*b}px`)}return{element:a}}static importJSON(a){let b=je();b.setFormat(a.format);b.setIndent(a.indent);b.setDirection(a.direction);b.setTextFormat(a.textFormat);return b}exportJSON(){return{...super.exportJSON(),textFormat:this.getTextFormat(),type:"paragraph",
version:1}}insertNewAfter(a,b){let c=je();c.setTextFormat(a.format);a=this.getDirection();c.setDirection(a);c.setFormat(this.getFormatType());this.insertAfter(c,b);return c}collapseAtStart(){let a=this.getChildren();if(0===a.length||B(a[0])&&""===a[0].getTextContent().trim()){if(null!==this.getNextSibling())return this.selectNext(),this.remove(),!0;if(null!==this.getPreviousSibling())return this.selectPrevious(),this.remove(),!0}return!1}}
function Lf(a){let b=je();a.style&&(b.setFormat(a.style.textAlign),a=parseInt(a.style.textIndent,10)/20,0<a&&b.setIndent(a));return{node:b}}function je(){return Dc(new Vd)}function yd(a){return a instanceof Vd}
function tf(a,b,c,d){let e=a._keyToDOMMap;e.clear();a._editorState=Df();a._pendingEditorState=d;a._compositionKey=null;a._dirtyType=0;a._cloneNotNeeded.clear();a._dirtyLeaves=new Set;a._dirtyElements.clear();a._normalizedNodes=new Set;a._updateTags=new Set;a._updates=[];a._blockCursorElement=null;d=a._observer;null!==d&&(d.disconnect(),a._observer=null);null!==b&&(b.textContent="");null!==c&&(c.textContent="",e.set("root",c))}
function Mf(a,b){let c=new Map,d=new Set,e=f=>{Object.keys(f).forEach(g=>{let h=c.get(g);void 0===h&&(h=[],c.set(g,h));h.push(f[g])})};a.forEach(f=>{let g=f.klass.importDOM;null==g||d.has(g)||(d.add(g),f=g.call(f.klass),null!==f&&e(f))});b&&e(b);return c}
class Nf{constructor(a,b,c,d,e,f,g){this._parentEditor=b;this._rootElement=null;this._editorState=a;this._compositionKey=this._pendingEditorState=null;this._deferred=[];this._keyToDOMMap=new Map;this._updates=[];this._updating=!1;this._listeners={decorator:new Set,editable:new Set,mutation:new Map,root:new Set,textcontent:new Set,update:new Set};this._commands=new Map;this._config=d;this._nodes=c;this._decorators={};this._pendingDecorators=null;this._dirtyType=0;this._cloneNotNeeded=new Set;this._dirtyLeaves=
new Set;this._dirtyElements=new Map;this._normalizedNodes=new Set;this._updateTags=new Set;this._observer=null;this._key=oc();this._onError=e;this._htmlConversions=f;this._editable=g;this._headless=null!==b&&b._headless;this._blockCursorElement=this._window=null}isComposing(){return null!=this._compositionKey}registerUpdateListener(a){let b=this._listeners.update;b.add(a);return()=>{b.delete(a)}}registerEditableListener(a){let b=this._listeners.editable;b.add(a);return()=>{b.delete(a)}}registerDecoratorListener(a){let b=
this._listeners.decorator;b.add(a);return()=>{b.delete(a)}}registerTextContentListener(a){let b=this._listeners.textcontent;b.add(a);return()=>{b.delete(a)}}registerRootListener(a){let b=this._listeners.root;a(this._rootElement,null);b.add(a);return()=>{a(null,this._rootElement);b.delete(a)}}registerCommand(a,b,c){void 0===c&&t(1);let d=this._commands;d.has(a)||d.set(a,[new Set,new Set,new Set,new Set,new Set]);let e=d.get(a);void 0===e&&t(2,String(a));let f=e[c];f.add(b);return()=>{f.delete(b);e.every(g=>
0===g.size)&&d.delete(a)}}registerMutationListener(a,b){let c=this._nodes.get(a.getType());void 0===c&&t(3,a.name);let d=null;for(;d=c.replaceWithKlass;)a=d,c=this._nodes.get(d.getType()),void 0===c&&t(3,d.name);let e=this._listeners.mutation;e.set(b,a);return()=>{e.delete(b)}}registerNodeTransformToKlass(a,b){var c=a.getType();c=this._nodes.get(c);void 0===c&&t(3,a.name);c.transforms.add(b);return c}registerNodeTransform(a,b){var c=this.registerNodeTransformToKlass(a,b);let d=[c];c=c.replaceWithKlass;
null!=c&&(c=this.registerNodeTransformToKlass(c,b),d.push(c));kc(this,a.getType());return()=>{d.forEach(e=>e.transforms.delete(b))}}hasNode(a){return this._nodes.has(a.getType())}hasNodes(a){return a.every(this.hasNode.bind(this))}dispatchCommand(a,b){return S(this,a,b)}getDecorators(){return this._decorators}getRootElement(){return this._rootElement}getKey(){return this._key}setRootElement(a){let b=this._rootElement;if(a!==b){let f=tc(this._config.theme,"root");var c=this._pendingEditorState||this._editorState;
this._rootElement=a;tf(this,b,a,c);if(null!==b){if(!this._config.disableEvents){var d=b.ownerDocument,e=Md.get(d);void 0===e&&t(54);--e;0<=e||t(55);Md.set(d,e);0===e&&d.removeEventListener("selectionchange",ce);d=b.__lexicalEditor;null!==d&&void 0!==d&&(null!==d._parentEditor?(e=nc(d),e=e[e.length-1]._key,be.get(e)===d&&be.delete(e)):be.delete(d._key),b.__lexicalEditor=null);d=ae(b);for(e=0;e<d.length;e++)d[e]();b.__lexicalEventHandles=[]}null!=f&&b.classList.remove(...f)}null!==a?(c=(c=a.ownerDocument)&&
c.defaultView||null,d=a.style,d.userSelect="text",d.whiteSpace="pre-wrap",d.wordBreak="break-word",a.setAttribute("data-lexical-editor","true"),this._window=c,this._dirtyType=2,Gb(this),this._updateTags.add("history-merge"),sf(this),this._config.disableEvents||de(a,this),null!=f&&a.classList.add(...f)):(this._editorState=c,this._window=this._pendingEditorState=null);uf("root",this,!1,a,b)}}getElementByKey(a){return this._keyToDOMMap.get(a)||null}getEditorState(){return this._editorState}setEditorState(a,
b){a.isEmpty()&&t(4);Fb(this);let c=this._pendingEditorState,d=this._updateTags;b=void 0!==b?b.tag:null;null===c||c.isEmpty()||(null!=b&&d.add(b),sf(this));this._pendingEditorState=a;this._dirtyType=2;this._dirtyElements.set("root",!1);this._compositionKey=null;null!=b&&d.add(b);sf(this)}parseEditorState(a,b){a="string"===typeof a?JSON.parse(a):a;let c=Df(),d=T,e=W,f=U,g=this._dirtyElements,h=this._dirtyLeaves,k=this._cloneNotNeeded,l=this._dirtyType;this._dirtyElements=new Map;this._dirtyLeaves=
new Set;this._cloneNotNeeded=new Set;this._dirtyType=0;T=c;W=!1;U=this;try{qf(a.root,this._nodes),b&&b(),c._readOnly=!0}catch(p){p instanceof Error&&this._onError(p)}finally{this._dirtyElements=g,this._dirtyLeaves=h,this._cloneNotNeeded=k,this._dirtyType=l,T=d,W=e,U=f}return c}update(a,b){v(this,a,b)}focus(a,b={}){let c=this._rootElement;null!==c&&(c.setAttribute("autocapitalize","off"),v(this,()=>{let d=u(),e=J();null!==d?d.dirty=!0:0!==e.getChildrenSize()&&("rootStart"===b.defaultSelection?e.selectStart():
e.selectEnd())},{onUpdate:()=>{c.removeAttribute("autocapitalize");a&&a()},tag:"focus"}),null===this._pendingEditorState&&c.removeAttribute("autocapitalize"))}blur(){var a=this._rootElement;null!==a&&a.blur();a=Ab(this._window);null!==a&&a.removeAllRanges()}isEditable(){return this._editable}setEditable(a){this._editable!==a&&(this._editable=a,uf("editable",this,!0,a))}toJSON(){return{editorState:this._editorState.toJSON()}}}exports.$addUpdateTag=function(a){G();F()._updateTags.add(a)};
exports.$applyNodeReplacement=Dc;exports.$copyNode=Cc;exports.$createLineBreakNode=oe;exports.$createNodeSelection=bf;exports.$createParagraphNode=je;exports.$createPoint=Se;exports.$createRangeSelection=function(){let a=Se("root",0,"element"),b=Se("root",0,"element");return new We(a,b,0,"")};exports.$createRangeSelectionFromDom=function(a,b){return Wd(null,a,b,null)};exports.$createTabNode=De;exports.$createTextNode=K;exports.$getAdjacentNode=wc;exports.$getCharacterOffsets=Xe;
exports.$getEditor=function(){return F()};exports.$getNearestNodeFromDOMNode=zb;exports.$getNearestRootOrShadowRoot=Ac;exports.$getNodeByKey=I;exports.$getNodeByKeyOrThrow=function(a){let b=I(a);null===b&&t(28,a);return b};exports.$getPreviousSelection=qc;exports.$getRoot=J;exports.$getSelection=u;exports.$getTextContent=function(){let a=u();return null===a?"":a.getTextContent()};exports.$hasAncestor=zc;exports.$hasUpdateTag=function(a){return F()._updateTags.has(a)};
exports.$insertNodes=function(a){let b=u()||qc();null===b&&(b=J().selectEnd());b.insertNodes(a)};exports.$isBlockElementNode=function(a){return E(a)&&!a.isInline()};exports.$isDecoratorNode=y;exports.$isElementNode=E;exports.$isInlineElementOrDecoratorNode=function(a){return E(a)&&a.isInline()||y(a)&&a.isInline()};exports.$isLeafNode=function(a){return B(a)||Kc(a)||y(a)};exports.$isLineBreakNode=Kc;exports.$isNodeSelection=$d;exports.$isParagraphNode=yd;exports.$isRangeSelection=C;
exports.$isRootNode=L;exports.$isRootOrShadowRoot=Bc;exports.$isTabNode=Qe;exports.$isTextNode=B;exports.$nodesOfType=function(a){var b=dc();let c=b._readOnly,d=a.getType();b=b._nodeMap;let e=[];for(let [,f]of b)f instanceof a&&f.__type===d&&(c||f.isAttached())&&e.push(f);return e};exports.$normalizeSelection__EXPERIMENTAL=Lb;exports.$parseSerializedNode=function(a){return qf(a,F()._nodes)};exports.$selectAll=function(){var a=J();a=a.select(0,a.getChildrenSize());Db(Lb(a))};
exports.$setCompositionKey=H;exports.$setSelection=Db;exports.$splitNode=function(a,b){let c=a.getChildAtIndex(b);null==c&&(c=a);Bc(a)&&t(29);let d=g=>{const h=g.getParentOrThrow(),k=Bc(h),l=g!==c||k?Cc(g):g;if(k)return E(g)&&E(l)||t(30),g.insertAfter(l),[g,l,l];const [p,q,m]=d(h);g=g.getNextSiblings();m.append(l,...g);return[p,q,l]},[e,f]=d(c);return[e,f]};exports.ArtificialNode__DO_NOT_USE=Kf;exports.BLUR_COMMAND=Sa;exports.CAN_REDO_COMMAND={};exports.CAN_UNDO_COMMAND={};
exports.CLEAR_EDITOR_COMMAND={};exports.CLEAR_HISTORY_COMMAND={};exports.CLICK_COMMAND=ca;exports.COMMAND_PRIORITY_CRITICAL=4;exports.COMMAND_PRIORITY_EDITOR=0;exports.COMMAND_PRIORITY_HIGH=3;exports.COMMAND_PRIORITY_LOW=1;exports.COMMAND_PRIORITY_NORMAL=2;exports.CONTROLLED_TEXT_INSERTION_COMMAND=ia;exports.COPY_COMMAND=Oa;exports.CUT_COMMAND=Pa;exports.DELETE_CHARACTER_COMMAND=da;exports.DELETE_LINE_COMMAND=pa;exports.DELETE_WORD_COMMAND=oa;exports.DRAGEND_COMMAND=Na;exports.DRAGOVER_COMMAND=Ma;
exports.DRAGSTART_COMMAND=La;exports.DROP_COMMAND=Ka;exports.DecoratorNode=Bf;exports.ElementNode=zf;exports.FOCUS_COMMAND=Ra;exports.FORMAT_ELEMENT_COMMAND={};exports.FORMAT_TEXT_COMMAND=ra;exports.INDENT_CONTENT_COMMAND={};exports.INSERT_LINE_BREAK_COMMAND=ea;exports.INSERT_PARAGRAPH_COMMAND=fa;exports.INSERT_TAB_COMMAND={};exports.IS_ALL_FORMATTING=255;exports.IS_BOLD=1;exports.IS_CODE=16;exports.IS_HIGHLIGHT=128;exports.IS_ITALIC=2;exports.IS_NORMAL=0;exports.IS_SEGMENTED=2;
exports.IS_STRIKETHROUGH=4;exports.IS_SUBSCRIPT=32;exports.IS_SUPERSCRIPT=64;exports.IS_TOKEN=1;exports.IS_UNDERLINE=8;exports.KEY_ARROW_DOWN_COMMAND=Ba;exports.KEY_ARROW_LEFT_COMMAND=xa;exports.KEY_ARROW_RIGHT_COMMAND=va;exports.KEY_ARROW_UP_COMMAND=Aa;exports.KEY_BACKSPACE_COMMAND=Ea;exports.KEY_DELETE_COMMAND=Ia;exports.KEY_DOWN_COMMAND=ua;exports.KEY_ENTER_COMMAND=Ca;exports.KEY_ESCAPE_COMMAND=Ha;exports.KEY_MODIFIER_COMMAND=Ta;exports.KEY_SPACE_COMMAND=Da;exports.KEY_TAB_COMMAND=Ja;
exports.LineBreakNode=le;exports.MOVE_TO_END=wa;exports.MOVE_TO_START=za;exports.OUTDENT_CONTENT_COMMAND={};exports.PASTE_COMMAND=ja;exports.ParagraphNode=Vd;exports.REDO_COMMAND=ta;exports.REMOVE_TEXT_COMMAND=na;exports.RootNode=Cf;exports.SELECTION_CHANGE_COMMAND=aa;exports.SELECTION_INSERT_CLIPBOARD_NODES_COMMAND={};exports.SELECT_ALL_COMMAND=Qa;exports.TEXT_TYPE_TO_FORMAT=ib;exports.TabNode=Pe;exports.TextNode=ue;exports.UNDO_COMMAND=sa;exports.createCommand=function(){return{}};
exports.createEditor=function(a){var b=a||{},c=U,d=b.theme||{};let e=void 0===a?c:b.parentEditor||null,f=b.disableEvents||!1,g=Df(),h=b.namespace||(null!==e?e._config.namespace:oc()),k=b.editorState,l=[Cf,ue,le,Pe,Vd,Kf,...(b.nodes||[])],{onError:p,html:q}=b;b=void 0!==b.editable?b.editable:!0;if(void 0===a&&null!==c)a=c._nodes;else for(a=new Map,c=0;c<l.length;c++){let r=l[c],w=null;var m=null;"function"!==typeof r&&(m=r,r=m.replace,w=m.with,m=m.withKlass||null);let A=r.getType(),x=r.transform(),
z=new Set;null!==x&&z.add(x);a.set(A,{exportDOM:q&&q.export?q.export.get(r):void 0,klass:r,replace:w,replaceWithKlass:m,transforms:z})}d=new Nf(g,e,a,{disableEvents:f,namespace:h,theme:d},p?p:console.error,Mf(a,q?q.import:void 0),b);void 0!==k&&(d._pendingEditorState=k,d._dirtyType=2);return d};exports.getActiveEditor=F;exports.getNearestEditorFromDOMNode=Rb;
exports.isBlockDomNode=function(a){return null!==a.nodeName.match(new RegExp(/^(address|article|aside|blockquote|canvas|dd|div|dl|dt|fieldset|figcaption|figure|footer|form|h1|h2|h3|h4|h5|h6|header|hr|li|main|nav|noscript|ol|p|pre|section|table|td|tfoot|ul|video)$/,"i"))};exports.isCurrentlyReadOnlyMode=hc;exports.isHTMLAnchorElement=function(a){return Hc(a)&&"A"===a.tagName};exports.isHTMLElement=Hc;exports.isInlineDomNode=Ic;exports.isSelectionCapturedInDecoratorInput=Pb;
exports.isSelectionWithinEditor=Qb;exports.resetRandomKey=function(){Nb=1}
